2025-03-21 13:18:14,209 - INFO - Starting the data processing pipeline.
2025-03-21 13:18:14,264 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001C173415A00>: Failed to resolve 'hostname.clickhouse.cloud' ([Errno 11001] getaddrinfo failed)")': /?
2025-03-21 13:18:14,267 - WARNING - Unexpected Http Driver Exception
2025-03-21 13:18:14,267 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='hostname.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001C172B91F40>: Failed to resolve 'hostname.clickhouse.cloud' ([Errno 11001] getaddrinfo failed)")) executing HTTP request attempt 1 (https://HOSTNAME.clickhouse.cloud:8443)
2025-03-21 13:19:56,126 - INFO - Starting the data processing pipeline.
2025-03-21 13:21:32,667 - ERROR - Failed to connect to ClickHouse: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 81
 Code: 81. DB::Exception: Database ah does not exist. (UNKNOWN_DATABASE) (version 24.10.1.11464 (official build))

2025-03-21 16:00:03,892 - INFO - Starting the data processing pipeline.
2025-03-21 16:00:05,573 - INFO - Connected to ClickHouse database.
2025-03-21 16:00:06,282 - INFO - Data processing pipeline completed successfully!
2025-03-21 16:00:30,414 - INFO - Starting the data processing pipeline.
2025-03-21 16:00:51,515 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001A308DA1610>, 'Connection to di33kgplgc.germanywestcentral.azure.clickhouse.cloud timed out. (connect timeout=10)')': /?
2025-03-21 16:01:00,264 - INFO - Connected to ClickHouse database.
2025-03-21 16:01:39,457 - INFO - Starting the data processing pipeline.
2025-03-21 16:01:42,192 - INFO - Connected to ClickHouse database.
2025-03-21 16:01:42,362 - INFO - Data processing pipeline completed successfully!
2025-03-21 17:27:49,542 - INFO - Starting the data processing pipeline.
2025-03-21 17:28:23,707 - INFO - Connected to ClickHouse database.
2025-03-21 17:28:24,174 - INFO - Connected to ClickHouse database.
2025-03-21 17:28:24,328 - ERROR - Error in fetching data: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 62
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 177 (end of query) (line 5, col 41): ;
        
 FORMAT Native. . (SYNTAX_ERROR) (version 24.10.1.11464 (official build))

2025-03-21 17:29:52,625 - INFO - Starting the data processing pipeline.
2025-03-21 17:29:54,608 - INFO - Connected to ClickHouse database.
2025-03-21 17:29:55,074 - INFO - Connected to ClickHouse database.
2025-03-21 17:29:55,074 - ERROR - Error in fetching data: 'HttpClient' object has no attribute 'execute'
2025-03-21 17:31:12,690 - INFO - Starting the data processing pipeline.
2025-03-21 17:31:15,383 - INFO - Connected to ClickHouse database.
2025-03-21 17:31:16,204 - INFO - Connected to ClickHouse database.
2025-03-21 17:31:16,208 - ERROR - Error in fetching data: 'HttpClient' object has no attribute 'execute'
2025-03-21 17:33:42,759 - INFO - Starting the data processing pipeline.
2025-03-21 17:33:45,817 - INFO - Connected to ClickHouse database.
2025-03-21 17:33:46,737 - INFO - Connected to ClickHouse database.
2025-03-21 17:33:46,738 - ERROR - Error in fetching data: 'HttpClient' object has no attribute 'execute'
2025-03-21 17:35:20,869 - INFO - Starting the data processing pipeline.
2025-03-21 17:35:24,648 - INFO - Connected to ClickHouse database.
2025-03-21 17:35:25,254 - INFO - Connected to ClickHouse database.
2025-03-21 17:35:25,400 - ERROR - Error in fetching data: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 62
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 60 (end of query) (line 4, col 18): ;
        
 FORMAT Native. . (SYNTAX_ERROR) (version 24.10.1.11464 (official build))

2025-03-21 17:36:25,948 - INFO - Starting the data processing pipeline.
2025-03-21 17:36:30,188 - INFO - Connected to ClickHouse database.
2025-03-21 17:36:30,793 - INFO - Connected to ClickHouse database.
2025-03-21 17:36:31,097 - ERROR - Error in fetching data: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 62
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 60 (end of query) (line 4, col 18): ;
        
 FORMAT Native. . (SYNTAX_ERROR) (version 24.10.1.11464 (official build))

2025-03-21 17:37:48,688 - INFO - Starting the data processing pipeline.
2025-03-21 17:37:51,547 - INFO - Connected to ClickHouse database.
2025-03-21 17:37:52,030 - INFO - Connected to ClickHouse database.
2025-03-21 17:37:52,180 - ERROR - Error in fetching data: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 62
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 60 (end of query) (line 4, col 18): ;
        
 FORMAT Native. . (SYNTAX_ERROR) (version 24.10.1.11464 (official build))

2025-03-21 17:42:13,065 - INFO - Starting the data processing pipeline.
2025-03-21 17:42:31,872 - INFO - Connected to ClickHouse database.
2025-03-21 17:42:36,699 - INFO - Connected to ClickHouse database.
2025-03-21 17:42:36,866 - ERROR - Error in fetching data: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 62
 Code: 62. DB::Exception: Syntax error: failed at position 78 ('LIMIT') (line 5, col 9): LIMIT 100;
        
 FORMAT Native. Expected one of: SETTINGS, end of query. (SYNTAX_ERROR) (version 24.10.1.11464 (official build))

2025-03-21 17:43:30,970 - INFO - Starting the data processing pipeline.
2025-03-21 17:43:38,431 - INFO - Connected to ClickHouse database.
2025-03-21 17:43:46,085 - INFO - Connected to ClickHouse database.
2025-03-21 17:43:46,242 - ERROR - Error in fetching data: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 62
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 69 (end of query) (line 4, col 27): ;
        
 FORMAT Native. . (SYNTAX_ERROR) (version 24.10.1.11464 (official build))

2025-03-21 17:44:24,365 - INFO - Starting the data processing pipeline.
2025-03-21 17:44:26,623 - INFO - Connected to ClickHouse database.
2025-03-21 17:44:27,097 - INFO - Connected to ClickHouse database.
2025-03-21 17:44:27,261 - ERROR - Error in fetching data: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 62
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 69 (end of query) (line 4, col 27): ;
        
 FORMAT Native. . (SYNTAX_ERROR) (version 24.10.1.11464 (official build))

2025-03-21 17:45:13,744 - INFO - Starting the data processing pipeline.
2025-03-21 17:45:18,578 - INFO - Connected to ClickHouse database.
2025-03-21 17:45:19,174 - INFO - Connected to ClickHouse database.
2025-03-21 17:45:19,324 - ERROR - Error in fetching data: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 62
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 69 (end of query) (line 4, col 27): ;
        
 FORMAT Native. . (SYNTAX_ERROR) (version 24.10.1.11464 (official build))

2025-03-21 17:47:26,741 - INFO - Starting the data processing pipeline.
2025-03-21 17:47:30,535 - INFO - Connected to ClickHouse database.
2025-03-21 17:47:31,410 - INFO - Connected to ClickHouse database.
2025-03-21 17:47:31,560 - ERROR - Error in fetching data: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 62
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 42 (end of query) (line 3, col 23): ;
        
 FORMAT Native. . (SYNTAX_ERROR) (version 24.10.1.11464 (official build))

2025-03-21 17:50:29,401 - INFO - Starting the data processing pipeline.
2025-03-21 17:50:44,445 - INFO - Starting the data processing pipeline.
2025-03-21 17:50:52,931 - INFO - Connected to ClickHouse database.
2025-03-21 17:50:52,933 - INFO - Connection is sorted
2025-03-21 17:50:54,325 - INFO - Connected to ClickHouse database.
2025-03-21 17:50:54,328 - INFO - Client Creds recieved
2025-03-21 17:50:54,476 - ERROR - Error in fetching data: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 62
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 42 (end of query) (line 3, col 23): ;
        
 FORMAT Native. . (SYNTAX_ERROR) (version 24.10.1.11464 (official build))

2025-03-21 17:51:58,638 - INFO - Starting the data processing pipeline.
2025-03-21 17:52:03,383 - INFO - Connected to ClickHouse database.
2025-03-21 17:52:03,416 - INFO - Connection is sorted
2025-03-21 17:52:04,268 - INFO - Connected to ClickHouse database.
2025-03-21 17:52:04,270 - INFO - Client Creds recieved
2025-03-21 17:52:04,427 - ERROR - Error in fetching data: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 62
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 42 (end of query) (line 3, col 23): ;
        
 FORMAT Native. . (SYNTAX_ERROR) (version 24.10.1.11464 (official build))

2025-03-21 17:53:14,901 - INFO - Starting the data processing pipeline.
2025-03-21 17:53:22,973 - INFO - Connected to ClickHouse database.
2025-03-21 17:53:22,974 - INFO - Connection is sorted
2025-03-21 17:53:24,357 - INFO - Connected to ClickHouse database.
2025-03-21 17:53:24,357 - INFO - Client Creds recieved
2025-03-21 17:53:24,518 - ERROR - Error in fetching data: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 62
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 42 (end of query) (line 2, col 41): ;
        
 FORMAT Native. . (SYNTAX_ERROR) (version 24.10.1.11464 (official build))

2025-03-21 17:54:15,243 - INFO - Starting the data processing pipeline.
2025-03-21 17:54:19,478 - INFO - Connected to ClickHouse database.
2025-03-21 17:54:19,479 - INFO - Connection is sorted
2025-03-21 17:54:20,599 - INFO - Connected to ClickHouse database.
2025-03-21 17:54:20,599 - INFO - Client Creds recieved
2025-03-21 17:54:20,780 - INFO - Query execution completed
2025-03-21 17:54:20,794 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-21 17:54:20,794 - INFO - Data processing pipeline completed successfully!
2025-03-21 17:55:47,607 - INFO - Starting the data processing pipeline.
2025-03-21 17:55:50,883 - INFO - Connected to ClickHouse database.
2025-03-21 17:55:50,883 - INFO - Connection is sorted
2025-03-21 17:55:51,384 - INFO - Connected to ClickHouse database.
2025-03-21 17:55:51,384 - INFO - Client Creds recieved
2025-03-21 17:55:51,569 - INFO - Query execution completed
2025-03-21 17:55:51,575 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-21 17:55:51,589 - INFO - Data transformed successfully.
2025-03-21 17:55:51,589 - INFO - Data processing pipeline completed successfully!
2025-03-21 17:56:28,546 - INFO - Starting the data processing pipeline.
2025-03-21 17:56:30,979 - INFO - Connected to ClickHouse database.
2025-03-21 17:56:30,979 - INFO - Connection is sorted
2025-03-21 17:56:31,462 - INFO - Connected to ClickHouse database.
2025-03-21 17:56:31,462 - INFO - Client Creds recieved
2025-03-21 17:56:31,618 - INFO - Query execution completed
2025-03-21 17:56:31,622 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-21 17:56:31,626 - INFO - Data transformed successfully.
2025-03-21 17:56:31,657 - INFO - Data processing pipeline completed successfully!
2025-03-21 17:59:46,368 - INFO - Starting the data processing pipeline.
2025-03-21 17:59:55,288 - INFO - Connected to ClickHouse database.
2025-03-21 17:59:55,288 - INFO - Connection is sorted
2025-03-21 17:59:56,358 - INFO - Connected to ClickHouse database.
2025-03-21 17:59:56,358 - INFO - Client Creds recieved
2025-03-21 17:59:56,544 - INFO - Query execution completed
2025-03-21 17:59:56,544 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-21 17:59:56,551 - INFO - Data transformed successfully.
2025-03-21 17:59:56,567 - INFO - Data processing pipeline completed successfully!
2025-03-23 16:18:47,952 - INFO - Starting the data processing pipeline.
2025-03-23 16:18:49,317 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-23 16:18:50,342 - WARNING - Unexpected Http Driver Exception
2025-03-23 16:18:50,342 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-23 16:20:49,382 - INFO - Starting the data processing pipeline.
2025-03-23 16:20:50,502 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-23 16:20:52,096 - WARNING - Unexpected Http Driver Exception
2025-03-23 16:20:52,096 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-23 16:31:11,851 - INFO - Starting the data processing pipeline.
2025-03-23 16:31:11,867 - ERROR - Failed to connect to ClickHouse: HttpClient.__init__() got an unexpected keyword argument 'protocol'
2025-03-23 16:32:18,646 - INFO - Starting the data processing pipeline.
2025-03-23 16:32:18,647 - ERROR - Failed to connect to ClickHouse: HttpClient.__init__() got an unexpected keyword argument 'protocol'
2025-03-23 16:32:30,147 - INFO - Starting the data processing pipeline.
2025-03-23 16:32:31,046 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-23 16:32:31,921 - WARNING - Unexpected Http Driver Exception
2025-03-23 16:32:31,921 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-24 10:48:00,424 - INFO - Starting the data processing pipeline.
2025-03-24 10:48:04,094 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-24 10:48:07,068 - WARNING - Unexpected Http Driver Exception
2025-03-24 10:48:07,068 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-24 10:49:21,353 - INFO - Starting the data processing pipeline.
2025-03-24 10:49:31,396 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000118C56B0200>, 'Connection to di33kgplgc.germanywestcentral.azure.clickhouse.cloud timed out. (connect timeout=10)')': /?
2025-03-24 10:49:41,407 - WARNING - Unexpected Http Driver Exception
2025-03-24 10:49:41,407 - ERROR - Failed to connect to ClickHouse: Error HTTPConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8123): Max retries exceeded with url: /? (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000118C5A10BC0>, 'Connection to di33kgplgc.germanywestcentral.azure.clickhouse.cloud timed out. (connect timeout=10)')) executing HTTP request attempt 1 (http://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8123)
2025-03-24 10:52:38,514 - INFO - Starting the data processing pipeline.
2025-03-24 10:52:41,025 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-24 10:52:42,959 - WARNING - Unexpected Http Driver Exception
2025-03-24 10:52:42,959 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-24 10:55:25,709 - INFO - Starting the data processing pipeline.
2025-03-24 10:55:27,007 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-24 10:55:29,348 - WARNING - Unexpected Http Driver Exception
2025-03-24 10:55:29,349 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-24 10:55:43,220 - INFO - Starting the data processing pipeline.
2025-03-24 10:55:53,251 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002326BEC1A60>, 'Connection to di33kgplgc.germanywestcentral.azure.clickhouse.cloud timed out. (connect timeout=10)')': /?
2025-03-24 10:56:03,259 - WARNING - Unexpected Http Driver Exception
2025-03-24 10:56:03,259 - ERROR - Failed to connect to ClickHouse: Error HTTPConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8123): Max retries exceeded with url: /? (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000232712A5C10>, 'Connection to di33kgplgc.germanywestcentral.azure.clickhouse.cloud timed out. (connect timeout=10)')) executing HTTP request attempt 1 (http://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8123)
2025-03-24 10:58:20,577 - INFO - Starting the data processing pipeline.
2025-03-24 10:58:24,968 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-24 10:58:27,262 - WARNING - Unexpected Http Driver Exception
2025-03-24 10:58:27,262 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-24 10:59:39,934 - INFO - Starting the data processing pipeline.
2025-03-24 10:59:42,008 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-24 10:59:44,161 - WARNING - Unexpected Http Driver Exception
2025-03-24 10:59:44,161 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-24 10:59:58,914 - INFO - Starting the data processing pipeline.
2025-03-24 10:59:59,868 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-24 11:00:00,804 - WARNING - Unexpected Http Driver Exception
2025-03-24 11:00:00,804 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-24 11:05:46,476 - INFO - Starting the data processing pipeline.
2025-03-24 11:05:56,187 - INFO - Connected to ClickHouse database.
2025-03-24 11:05:56,188 - INFO - Connection is Done
2025-03-24 11:05:56,733 - INFO - Connected to ClickHouse database.
2025-03-24 11:05:56,733 - INFO - Client Creds recieved
2025-03-24 11:05:56,910 - INFO - Query execution completed
2025-03-24 11:05:56,912 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 11:05:56,926 - INFO - Data transformed successfully.
2025-03-24 11:05:56,953 - INFO - Data processing pipeline completed successfully!
2025-03-24 11:33:27,815 - INFO - Starting the data processing pipeline.
2025-03-24 11:35:22,106 - INFO - Connected to ClickHouse database.
2025-03-24 11:35:22,106 - ERROR - Error in fetching schema: 'HttpClient' object has no attribute 'execute'
2025-03-24 11:36:02,326 - INFO - Starting the data processing pipeline.
2025-03-24 11:38:25,222 - INFO - Starting the data processing pipeline.
2025-03-24 11:38:33,055 - INFO - Connected to ClickHouse database.
2025-03-24 11:38:33,055 - ERROR - Error in fetching schema: 'HttpClient' object has no attribute 'execute'
2025-03-24 11:39:37,526 - INFO - Starting the data processing pipeline.
2025-03-24 11:39:48,565 - INFO - Connected to ClickHouse database.
2025-03-24 11:39:48,873 - ERROR - Error in fetching schema: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 60
 Code: 60. DB::Exception: Table AH.final_data does not exist. Maybe you meant AH.bank_data?. (UNKNOWN_TABLE) (version 24.10.1.11464 (official build))

2025-03-24 11:53:01,196 - INFO - Starting the data processing pipeline.
2025-03-24 11:53:04,678 - INFO - Connected to ClickHouse database.
2025-03-24 11:53:05,217 - INFO - Connected to ClickHouse database.
2025-03-24 11:53:05,220 - ERROR - Error in ensuring table: 'HttpClient' object has no attribute 'execute'
2025-03-24 11:53:28,385 - INFO - Starting the data processing pipeline.
2025-03-24 11:53:43,197 - INFO - Connected to ClickHouse database.
2025-03-24 11:53:45,379 - INFO - Connected to ClickHouse database.
2025-03-24 11:53:45,599 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 11:53:50,911 - INFO - Connected to ClickHouse database.
2025-03-24 11:53:50,911 - INFO - Client Creds recieved
2025-03-24 11:53:51,317 - INFO - Query execution completed
2025-03-24 11:53:51,321 - ERROR - Error in fetching data: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2025-03-24 11:55:53,797 - INFO - Starting the data processing pipeline.
2025-03-24 11:55:59,157 - INFO - Connected to ClickHouse database.
2025-03-24 11:55:59,826 - INFO - Connected to ClickHouse database.
2025-03-24 11:55:59,995 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 11:56:00,495 - INFO - Connected to ClickHouse database.
2025-03-24 11:56:00,496 - INFO - Client Creds recieved
2025-03-24 11:56:00,665 - INFO - Query execution completed
2025-03-24 11:56:00,666 - ERROR - Error in fetching data: 0
2025-03-24 11:56:58,520 - INFO - Starting the data processing pipeline.
2025-03-24 11:57:03,758 - INFO - Connected to ClickHouse database.
2025-03-24 11:57:04,369 - INFO - Connected to ClickHouse database.
2025-03-24 11:57:04,835 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 11:57:05,416 - INFO - Connected to ClickHouse database.
2025-03-24 11:57:05,416 - INFO - Client Creds recieved
2025-03-24 11:57:05,588 - INFO - Query execution completed
2025-03-24 11:57:05,589 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 11:57:05,589 - ERROR - Error in data transformation: 'Total_Transactions'
2025-03-24 11:57:54,244 - INFO - Starting the data processing pipeline.
2025-03-24 11:57:59,492 - INFO - Connected to ClickHouse database.
2025-03-24 11:57:59,991 - INFO - Connected to ClickHouse database.
2025-03-24 11:58:00,166 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 11:58:00,642 - INFO - Connected to ClickHouse database.
2025-03-24 11:58:00,643 - INFO - Client Creds recieved
2025-03-24 11:58:00,868 - INFO - Query execution completed
2025-03-24 11:58:00,868 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 11:58:00,885 - INFO - Data transformed successfully.
2025-03-24 11:58:01,397 - INFO - Connected to ClickHouse database.
2025-03-24 11:58:01,399 - ERROR - Error in inserting data: 'HttpClient' object has no attribute 'execute'
2025-03-24 11:58:25,836 - INFO - Starting the data processing pipeline.
2025-03-24 11:58:29,771 - INFO - Connected to ClickHouse database.
2025-03-24 11:58:30,245 - INFO - Connected to ClickHouse database.
2025-03-24 11:58:30,421 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 11:58:30,910 - INFO - Connected to ClickHouse database.
2025-03-24 11:58:30,910 - INFO - Client Creds recieved
2025-03-24 11:58:31,095 - INFO - Query execution completed
2025-03-24 11:58:31,095 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 11:58:31,104 - INFO - Data transformed successfully.
2025-03-24 11:58:31,609 - INFO - Connected to ClickHouse database.
2025-03-24 11:58:31,665 - ERROR - Error in inserting data: not all arguments converted during string formatting
2025-03-24 11:59:22,348 - INFO - Starting the data processing pipeline.
2025-03-24 11:59:25,083 - INFO - Connected to ClickHouse database.
2025-03-24 11:59:26,310 - INFO - Connected to ClickHouse database.
2025-03-24 11:59:26,514 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 11:59:27,068 - INFO - Connected to ClickHouse database.
2025-03-24 11:59:27,068 - INFO - Client Creds recieved
2025-03-24 11:59:27,263 - INFO - Query execution completed
2025-03-24 11:59:27,265 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 11:59:27,270 - INFO - Data transformed successfully.
2025-03-24 11:59:30,503 - INFO - Connected to ClickHouse database.
2025-03-24 11:59:30,675 - ERROR - Error in inserting data: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 60
 Code: 60. DB::Exception: Table AH.`INSERT INTO final_test (Domain,Location,Date,TotalTx ) VALUES` does not exist. (UNKNOWN_TABLE) (version 24.10.1.11464 (official build))

2025-03-24 12:01:52,396 - INFO - Starting the data processing pipeline.
2025-03-24 12:01:58,156 - INFO - Connected to ClickHouse database.
2025-03-24 12:01:58,728 - INFO - Connected to ClickHouse database.
2025-03-24 12:01:58,907 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 12:01:59,456 - INFO - Connected to ClickHouse database.
2025-03-24 12:01:59,458 - INFO - Client Creds recieved
2025-03-24 12:01:59,635 - INFO - Query execution completed
2025-03-24 12:01:59,635 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 12:01:59,640 - INFO - Data transformed successfully.
2025-03-24 12:02:00,155 - INFO - Connected to ClickHouse database.
2025-03-24 12:02:00,387 - ERROR - Error in inserting data: Insert data column count does not match column names
2025-03-24 12:03:51,438 - INFO - Starting the data processing pipeline.
2025-03-24 12:03:55,066 - INFO - Connected to ClickHouse database.
2025-03-24 12:03:55,623 - INFO - Connected to ClickHouse database.
2025-03-24 12:03:55,816 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 12:03:56,316 - INFO - Connected to ClickHouse database.
2025-03-24 12:03:56,316 - INFO - Client Creds recieved
2025-03-24 12:03:56,487 - INFO - Query execution completed
2025-03-24 12:03:56,487 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 12:03:56,493 - INFO - Data transformed successfully.
2025-03-24 12:03:57,127 - INFO - Connected to ClickHouse database.
2025-03-24 12:03:58,956 - INFO - Final data inserted successfully into 'final_table' in 'AH' database.
2025-03-24 12:03:58,957 - INFO - Data processing pipeline completed successfully!2025-03-24 12:44:18,678 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 12:44:18,690 - INFO - Starting data processing for queries\test1.py
2025-03-24 12:44:20,619 - INFO - Connected to ClickHouse database.
2025-03-24 12:44:20,619 - ERROR - Error in processing queries\test1.py: name 'create_table_query' is not defined
2025-03-24 12:44:20,632 - INFO - Starting data processing for queries\test2.py
2025-03-24 12:44:21,130 - INFO - Connected to ClickHouse database.
2025-03-24 12:44:21,130 - ERROR - Error in processing queries\test2.py: name 'create_table_query' is not defined
2025-03-24 12:44:21,130 - INFO - All query files processed successfully!
2025-03-24 12:46:58,630 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 12:46:58,642 - INFO - Starting data processing for queries\test1.py
2025-03-24 12:47:00,743 - INFO - Connected to ClickHouse database.
2025-03-24 12:47:01,269 - INFO - Connected to ClickHouse database.
2025-03-24 12:47:01,489 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 12:47:01,960 - INFO - Connected to ClickHouse database.
2025-03-24 12:47:01,968 - INFO - Client Creds recieved
2025-03-24 12:47:02,135 - INFO - Query execution completed
2025-03-24 12:47:02,135 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 12:47:02,138 - INFO - Data transformed successfully.
2025-03-24 12:47:02,618 - INFO - Connected to ClickHouse database.
2025-03-24 12:47:03,029 - ERROR - Error in inserting data: log() got multiple values for argument 'level'
2025-03-24 12:47:03,029 - ERROR - Error in processing queries\test1.py: log() got multiple values for argument 'level'
2025-03-24 12:47:03,029 - INFO - Starting data processing for queries\test2.py
2025-03-24 12:47:03,509 - INFO - Connected to ClickHouse database.
2025-03-24 12:47:03,992 - INFO - Connected to ClickHouse database.
2025-03-24 12:47:04,169 - ERROR - Error in ensuring table: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 47
 Code: 47. DB::Exception: Missing columns: 'Domain' while processing query: 'Domain, Date', required columns: 'Domain' 'Date' 'Domain' 'Date'. (UNKNOWN_IDENTIFIER) (version 24.10.1.11464 (official build))

2025-03-24 12:47:04,169 - ERROR - Error in processing queries\test2.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 47
 Code: 47. DB::Exception: Missing columns: 'Domain' while processing query: 'Domain, Date', required columns: 'Domain' 'Date' 'Domain' 'Date'. (UNKNOWN_IDENTIFIER) (version 24.10.1.11464 (official build))

2025-03-24 12:47:04,169 - INFO - All query files processed successfully!
2025-03-24 12:55:42,842 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 12:55:42,853 - INFO - Starting data processing for queries\test1.py
2025-03-24 12:55:44,736 - INFO - Connected to ClickHouse database.
2025-03-24 12:55:45,293 - INFO - Connected to ClickHouse database.
2025-03-24 12:55:45,474 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 12:55:45,955 - INFO - Connected to ClickHouse database.
2025-03-24 12:55:45,955 - INFO - Client Creds recieved
2025-03-24 12:55:46,114 - INFO - Query execution completed
2025-03-24 12:55:46,114 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 12:55:46,114 - ERROR - Error in processing queries\test1.py: name 'log' is not defined
2025-03-24 12:55:46,114 - ERROR - Error in processing queries\test2.py: Missing required variables or function
2025-03-24 12:55:46,114 - INFO - All query files processed successfully!
2025-03-24 12:59:09,333 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 12:59:09,352 - ERROR - Error in processing queries\test1.py: name '__file__' is not defined
2025-03-24 12:59:09,353 - ERROR - Error in processing queries\test2.py: Missing required variables or function
2025-03-24 12:59:09,354 - INFO - All query files processed successfully!
2025-03-24 13:01:29,573 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 13:01:29,604 - INFO - Starting data processing for queries\test1.py
2025-03-24 13:01:31,433 - INFO - Connected to ClickHouse database.
2025-03-24 13:01:32,002 - INFO - Connected to ClickHouse database.
2025-03-24 13:01:32,204 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 13:01:32,703 - INFO - Connected to ClickHouse database.
2025-03-24 13:01:32,703 - INFO - Client Creds recieved
2025-03-24 13:01:32,875 - INFO - Query execution completed
2025-03-24 13:01:32,875 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 13:01:32,877 - ERROR - Error in processing queries\test1.py: name 'log' is not defined
2025-03-24 13:01:32,877 - ERROR - Error in processing queries\test2.py: Missing required variables or function
2025-03-24 13:01:32,877 - INFO - All query files processed successfully!
2025-03-24 13:12:53,597 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 13:12:53,620 - INFO - Starting data processing for queries\test1.py
2025-03-24 13:12:55,440 - INFO - Connected to ClickHouse database.
2025-03-24 13:12:55,918 - INFO - Connected to ClickHouse database.
2025-03-24 13:12:56,092 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 13:12:56,559 - INFO - Connected to ClickHouse database.
2025-03-24 13:12:56,559 - INFO - Client Creds recieved
2025-03-24 13:12:56,742 - INFO - Query execution completed
2025-03-24 13:12:56,742 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 13:12:56,743 - ERROR - Error in processing queries\test1.py: name 'log' is not defined
2025-03-24 13:12:56,745 - ERROR - Error in processing queries\test2.py: Missing required variables or function
2025-03-24 13:12:56,745 - INFO - All query files processed successfully!
2025-03-24 13:14:04,381 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 13:14:04,399 - INFO - Starting data processing for queries\test1.py
2025-03-24 13:14:06,080 - INFO - Connected to ClickHouse database.
2025-03-24 13:14:06,559 - INFO - Connected to ClickHouse database.
2025-03-24 13:14:06,733 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 13:14:07,205 - INFO - Connected to ClickHouse database.
2025-03-24 13:14:07,206 - INFO - Client Creds recieved
2025-03-24 13:14:07,362 - INFO - Query execution completed
2025-03-24 13:14:07,363 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 13:14:07,364 - ERROR - Error in processing queries\test1.py: name 'log' is not defined
2025-03-24 13:14:07,366 - ERROR - Error in processing queries\test2.py: Missing required variables or function
2025-03-24 13:14:07,367 - INFO - All query files processed successfully!
2025-03-24 13:15:10,746 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 13:15:10,767 - INFO - Starting data processing for queries\test1.py
2025-03-24 13:15:13,637 - INFO - Connected to ClickHouse database.
2025-03-24 13:15:14,155 - INFO - Connected to ClickHouse database.
2025-03-24 13:15:14,336 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 13:15:14,817 - INFO - Connected to ClickHouse database.
2025-03-24 13:15:14,817 - INFO - Client Creds recieved
2025-03-24 13:15:14,977 - INFO - Query execution completed
2025-03-24 13:15:14,977 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 13:15:14,979 - ERROR - Error in processing queries\test1.py: name 'log' is not defined
2025-03-24 13:15:14,979 - ERROR - Error in processing queries\test2.py: Missing required variables or function
2025-03-24 13:15:14,979 - INFO - All query files processed successfully!
2025-03-24 13:16:35,838 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 13:16:35,867 - INFO - Starting data processing for queries\test1.py
2025-03-24 13:16:37,781 - INFO - Connected to ClickHouse database.
2025-03-24 13:16:38,270 - INFO - Connected to ClickHouse database.
2025-03-24 13:16:38,447 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 13:16:38,916 - INFO - Connected to ClickHouse database.
2025-03-24 13:16:38,916 - INFO - Client Creds recieved
2025-03-24 13:16:39,076 - INFO - Query execution completed
2025-03-24 13:16:39,076 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 13:16:39,083 - ERROR - Error in processing queries\test1.py: name 'log' is not defined
2025-03-24 13:16:39,083 - ERROR - Error in processing queries\test2.py: Missing required variables or function
2025-03-24 13:16:39,085 - INFO - All query files processed successfully!
2025-03-24 13:17:01,829 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 13:17:01,851 - INFO - Starting data processing for queries\test1.py
2025-03-24 13:17:03,740 - INFO - Connected to ClickHouse database.
2025-03-24 13:17:04,229 - INFO - Connected to ClickHouse database.
2025-03-24 13:17:04,406 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 13:17:04,877 - INFO - Connected to ClickHouse database.
2025-03-24 13:17:04,877 - INFO - Client Creds recieved
2025-03-24 13:17:05,035 - INFO - Query execution completed
2025-03-24 13:17:05,035 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 13:17:05,035 - ERROR - Error in processing queries\test1.py: name 'log' is not defined
2025-03-24 13:17:05,035 - ERROR - Error in processing queries\test2.py: Missing required variables or function
2025-03-24 13:17:05,035 - INFO - All query files processed successfully!
2025-03-24 13:21:40,448 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 13:21:40,451 - INFO - Starting data processing for queries\test1.py
2025-03-24 13:21:43,249 - INFO - Connected to ClickHouse database.
2025-03-24 13:21:43,733 - INFO - Connected to ClickHouse database.
2025-03-24 13:21:43,908 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 13:21:44,403 - INFO - Connected to ClickHouse database.
2025-03-24 13:21:44,403 - INFO - Client Creds recieved
2025-03-24 13:21:44,557 - INFO - Query execution completed
2025-03-24 13:21:44,558 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 13:21:44,559 - ERROR - Error in processing queries\test1.py: 'level' is an invalid keyword argument for print()
2025-03-24 13:21:44,576 - INFO - Starting data processing for queries\test2.py
2025-03-24 13:21:45,043 - INFO - Connected to ClickHouse database.
2025-03-24 13:21:45,509 - INFO - Connected to ClickHouse database.
2025-03-24 13:21:45,684 - ERROR - Error in ensuring table: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 47
 Code: 47. DB::Exception: Missing columns: 'Domain' while processing query: 'Domain, Date', required columns: 'Domain' 'Date' 'Domain' 'Date'. (UNKNOWN_IDENTIFIER) (version 24.10.1.11464 (official build))

2025-03-24 13:21:45,685 - ERROR - Error in processing queries\test2.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 47
 Code: 47. DB::Exception: Missing columns: 'Domain' while processing query: 'Domain, Date', required columns: 'Domain' 'Date' 'Domain' 'Date'. (UNKNOWN_IDENTIFIER) (version 24.10.1.11464 (official build))

2025-03-24 13:21:45,686 - INFO - All query files processed successfully!
2025-03-24 13:22:57,515 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 13:22:57,534 - INFO - Starting data processing for queries\test1.py
2025-03-24 13:23:00,318 - INFO - Connected to ClickHouse database.
2025-03-24 13:23:00,813 - INFO - Connected to ClickHouse database.
2025-03-24 13:23:00,986 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 13:23:01,460 - INFO - Connected to ClickHouse database.
2025-03-24 13:23:01,460 - INFO - Client Creds recieved
2025-03-24 13:23:01,627 - INFO - Query execution completed
2025-03-24 13:23:01,628 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 13:23:02,119 - INFO - Connected to ClickHouse database.
2025-03-24 13:23:02,443 - ERROR - Error in inserting data: log() got multiple values for argument 'level'
2025-03-24 13:23:02,444 - ERROR - Error in processing queries\test1.py: log() got multiple values for argument 'level'
2025-03-24 13:23:02,465 - INFO - Starting data processing for queries\test2.py
2025-03-24 13:23:02,945 - INFO - Connected to ClickHouse database.
2025-03-24 13:23:03,423 - INFO - Connected to ClickHouse database.
2025-03-24 13:23:03,646 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 13:23:04,146 - INFO - Connected to ClickHouse database.
2025-03-24 13:23:04,149 - INFO - Client Creds recieved
2025-03-24 13:23:04,303 - INFO - Query execution completed
2025-03-24 13:23:04,305 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 13:23:04,787 - INFO - Connected to ClickHouse database.
2025-03-24 13:23:05,133 - ERROR - Error in inserting data: log() got multiple values for argument 'level'
2025-03-24 13:23:05,133 - ERROR - Error in processing queries\test2.py: log() got multiple values for argument 'level'
2025-03-24 13:23:05,134 - INFO - All query files processed successfully!
2025-03-24 13:23:26,853 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 13:23:26,870 - INFO - Starting data processing for queries\test1.py
2025-03-24 13:23:29,632 - INFO - Connected to ClickHouse database.
2025-03-24 13:23:30,097 - INFO - Connected to ClickHouse database.
2025-03-24 13:23:30,270 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 13:23:30,735 - INFO - Connected to ClickHouse database.
2025-03-24 13:23:30,735 - INFO - Client Creds recieved
2025-03-24 13:23:30,915 - INFO - Query execution completed
2025-03-24 13:23:30,916 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 13:23:31,426 - INFO - Connected to ClickHouse database.
2025-03-24 13:23:31,755 - ERROR - Error in inserting data: log() got multiple values for argument 'level'
2025-03-24 13:23:31,755 - ERROR - Error in processing queries\test1.py: log() got multiple values for argument 'level'
2025-03-24 13:23:31,774 - INFO - Starting data processing for queries\test2.py
2025-03-24 13:23:32,553 - INFO - Connected to ClickHouse database.
2025-03-24 13:23:33,040 - INFO - Connected to ClickHouse database.
2025-03-24 13:23:33,218 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 13:23:33,690 - INFO - Connected to ClickHouse database.
2025-03-24 13:23:33,691 - INFO - Client Creds recieved
2025-03-24 13:23:33,847 - INFO - Query execution completed
2025-03-24 13:23:33,848 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 13:23:34,327 - INFO - Connected to ClickHouse database.
2025-03-24 13:23:34,655 - ERROR - Error in inserting data: log() got multiple values for argument 'level'
2025-03-24 13:23:34,656 - ERROR - Error in processing queries\test2.py: log() got multiple values for argument 'level'
2025-03-24 13:23:34,657 - INFO - All query files processed successfully!
2025-03-24 13:24:33,818 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 13:24:33,820 - INFO - Starting data processing for queries\test1.py
2025-03-24 13:24:35,583 - INFO - Connected to ClickHouse database.
2025-03-24 13:24:36,204 - INFO - Connected to ClickHouse database.
2025-03-24 13:24:36,427 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 13:24:37,043 - INFO - Connected to ClickHouse database.
2025-03-24 13:24:37,045 - INFO - Client Creds recieved
2025-03-24 13:24:37,217 - INFO - Query execution completed
2025-03-24 13:24:37,218 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 13:24:37,843 - INFO - Connected to ClickHouse database.
2025-03-24 13:24:38,157 - INFO - Final data inserted successfully into clickhouse
2025-03-24 13:24:38,158 - INFO - Data processing pipeline for queries\test1.py completed successfully!
2025-03-24 13:24:38,159 - INFO - Starting data processing for queries\test2.py
2025-03-24 13:24:38,797 - INFO - Connected to ClickHouse database.
2025-03-24 13:24:39,262 - INFO - Connected to ClickHouse database.
2025-03-24 13:24:39,437 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 13:24:39,895 - INFO - Connected to ClickHouse database.
2025-03-24 13:24:39,896 - INFO - Client Creds recieved
2025-03-24 13:24:40,069 - INFO - Query execution completed
2025-03-24 13:24:40,070 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 13:24:40,918 - INFO - Connected to ClickHouse database.
2025-03-24 13:24:41,288 - INFO - Final data inserted successfully into clickhouse
2025-03-24 13:24:41,289 - INFO - Data processing pipeline for queries\test2.py completed successfully!
2025-03-24 13:24:41,290 - INFO - All query files processed successfully!
2025-03-24 13:25:11,221 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 13:25:11,223 - INFO - Starting data processing for queries\test1.py
2025-03-24 13:25:13,312 - INFO - Connected to ClickHouse database.
2025-03-24 13:25:13,848 - INFO - Connected to ClickHouse database.
2025-03-24 13:25:14,035 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 13:25:14,610 - INFO - Connected to ClickHouse database.
2025-03-24 13:25:14,611 - INFO - Client Creds recieved
2025-03-24 13:25:14,785 - INFO - Query execution completed
2025-03-24 13:25:14,785 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 13:25:15,317 - INFO - Connected to ClickHouse database.
2025-03-24 13:25:15,651 - INFO - Final data inserted successfully into clickhouse for table {output_table_name}
2025-03-24 13:25:15,652 - INFO - Data processing pipeline for queries\test1.py completed successfully!
2025-03-24 13:25:15,653 - INFO - Starting data processing for queries\test2.py
2025-03-24 13:25:16,150 - INFO - Connected to ClickHouse database.
2025-03-24 13:25:16,706 - INFO - Connected to ClickHouse database.
2025-03-24 13:25:16,893 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 13:25:17,392 - INFO - Connected to ClickHouse database.
2025-03-24 13:25:17,392 - INFO - Client Creds recieved
2025-03-24 13:25:17,564 - INFO - Query execution completed
2025-03-24 13:25:17,564 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 13:25:18,060 - INFO - Connected to ClickHouse database.
2025-03-24 13:25:18,405 - INFO - Final data inserted successfully into clickhouse for table {output_table_name}
2025-03-24 13:25:18,405 - INFO - Data processing pipeline for queries\test2.py completed successfully!
2025-03-24 13:25:18,406 - INFO - All query files processed successfully!
2025-03-24 13:26:28,357 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 13:26:28,357 - INFO - Starting data processing for queries\test1.py
2025-03-24 13:26:31,237 - INFO - Connected to ClickHouse database.
2025-03-24 13:26:31,716 - INFO - Connected to ClickHouse database.
2025-03-24 13:26:31,896 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 13:26:32,586 - INFO - Connected to ClickHouse database.
2025-03-24 13:26:32,586 - INFO - Client Creds recieved
2025-03-24 13:26:32,755 - INFO - Query execution completed
2025-03-24 13:26:32,755 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 13:26:33,287 - INFO - Connected to ClickHouse database.
2025-03-24 13:26:33,610 - INFO - Final data inserted successfully into clickhouse for table test1
2025-03-24 13:26:33,610 - INFO - Data processing pipeline for queries\test1.py completed successfully!
2025-03-24 13:26:33,612 - INFO - Starting data processing for queries\test2.py
2025-03-24 13:26:34,097 - INFO - Connected to ClickHouse database.
2025-03-24 13:26:34,582 - INFO - Connected to ClickHouse database.
2025-03-24 13:26:34,762 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 13:26:35,215 - INFO - Connected to ClickHouse database.
2025-03-24 13:26:35,215 - INFO - Client Creds recieved
2025-03-24 13:26:35,377 - INFO - Query execution completed
2025-03-24 13:26:35,377 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 13:26:35,847 - INFO - Connected to ClickHouse database.
2025-03-24 13:26:36,181 - INFO - Final data inserted successfully into clickhouse for table test2
2025-03-24 13:26:36,181 - INFO - Data processing pipeline for queries\test2.py completed successfully!
2025-03-24 13:26:36,181 - INFO - All query files processed successfully!
2025-03-24 15:07:32,900 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 15:07:32,902 - INFO - Starting data processing for queries\test1.py
2025-03-24 15:07:35,892 - INFO - Connected to ClickHouse database.
2025-03-24 15:07:36,560 - INFO - Connected to ClickHouse database.
2025-03-24 15:07:36,737 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 15:07:36,804 - ERROR - Failed to connect to MySQL: Authentication plugin 'caching_sha2_password' is not supported
2025-03-24 15:07:36,804 - ERROR - Error in fetching data: Authentication plugin 'caching_sha2_password' is not supported
2025-03-24 15:07:36,804 - ERROR - Error in processing queries\test1.py: cannot access local variable 'client' where it is not associated with a value
2025-03-24 15:07:36,805 - INFO - Starting data processing for queries\test2.py
2025-03-24 15:07:37,277 - INFO - Connected to ClickHouse database.
2025-03-24 15:07:37,763 - INFO - Connected to ClickHouse database.
2025-03-24 15:07:37,937 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 15:07:37,939 - ERROR - Failed to connect to MySQL: Authentication plugin 'caching_sha2_password' is not supported
2025-03-24 15:07:37,939 - ERROR - Error in fetching data: Authentication plugin 'caching_sha2_password' is not supported
2025-03-24 15:07:37,939 - ERROR - Error in processing queries\test2.py: cannot access local variable 'client' where it is not associated with a value
2025-03-24 15:07:37,939 - INFO - All query files processed successfully!
2025-03-24 15:11:06,689 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 15:11:06,689 - INFO - Starting data processing for queries\test1.py
2025-03-24 15:11:09,557 - INFO - Connected to ClickHouse database.
2025-03-24 15:11:10,097 - INFO - Connected to ClickHouse database.
2025-03-24 15:11:10,294 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 15:11:10,297 - ERROR - Failed to connect to MySQL: Authentication plugin 'caching_sha2_password' is not supported
2025-03-24 15:11:10,297 - ERROR - Error in fetching data: Authentication plugin 'caching_sha2_password' is not supported
2025-03-24 15:11:10,297 - ERROR - Error in processing queries\test1.py: cannot access local variable 'client' where it is not associated with a value
2025-03-24 15:11:10,297 - INFO - Starting data processing for queries\test2.py
2025-03-24 15:11:10,791 - INFO - Connected to ClickHouse database.
2025-03-24 15:11:11,293 - INFO - Connected to ClickHouse database.
2025-03-24 15:11:11,486 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 15:11:11,489 - ERROR - Failed to connect to MySQL: Authentication plugin 'caching_sha2_password' is not supported
2025-03-24 15:11:11,489 - ERROR - Error in fetching data: Authentication plugin 'caching_sha2_password' is not supported
2025-03-24 15:11:11,489 - ERROR - Error in processing queries\test2.py: cannot access local variable 'client' where it is not associated with a value
2025-03-24 15:11:11,489 - INFO - All query files processed successfully!
2025-03-24 15:14:44,159 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 15:14:44,167 - INFO - Starting data processing for queries\test1.py
2025-03-24 15:14:45,917 - INFO - Connected to ClickHouse database.
2025-03-24 15:14:46,387 - INFO - Connected to ClickHouse database.
2025-03-24 15:14:46,557 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 15:14:46,581 - INFO - Connected to MySQL database.
2025-03-24 15:14:46,581 - INFO - Client creds received
2025-03-24 15:14:48,371 - INFO - Query execution completed
2025-03-24 15:14:48,374 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 15:14:48,374 - INFO - MySQL connection closed.
2025-03-24 15:14:49,177 - INFO - Connected to ClickHouse database.
2025-03-24 15:14:49,898 - INFO - Final data inserted successfully into clickhouse for table test1
2025-03-24 15:14:49,898 - INFO - Data processing pipeline for queries\test1.py completed successfully!
2025-03-24 15:14:49,898 - INFO - Starting data processing for queries\test2.py
2025-03-24 15:14:50,527 - INFO - Connected to ClickHouse database.
2025-03-24 15:14:51,017 - INFO - Connected to ClickHouse database.
2025-03-24 15:14:51,192 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 15:14:51,209 - INFO - Connected to MySQL database.
2025-03-24 15:14:51,210 - INFO - Client creds received
2025-03-24 15:14:52,090 - INFO - Query execution completed
2025-03-24 15:14:52,090 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 15:14:52,090 - INFO - MySQL connection closed.
2025-03-24 15:14:52,759 - INFO - Connected to ClickHouse database.
2025-03-24 15:14:53,150 - INFO - Final data inserted successfully into clickhouse for table test2
2025-03-24 15:14:53,150 - INFO - Data processing pipeline for queries\test2.py completed successfully!
2025-03-24 15:14:53,150 - INFO - All query files processed successfully!
2025-03-24 15:21:33,599 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 15:21:33,603 - INFO - Starting data processing for queries\test1.py
2025-03-24 15:21:36,409 - INFO - Connected to ClickHouse database.
2025-03-24 15:21:36,892 - INFO - Connected to ClickHouse database.
2025-03-24 15:21:37,069 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 15:21:37,087 - INFO - Connected to MySQL database.
2025-03-24 15:21:37,087 - INFO - Client creds received
2025-03-24 15:21:38,749 - INFO - Query execution completed
2025-03-24 15:21:38,749 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 15:21:38,749 - INFO - MySQL connection closed.
2025-03-24 15:21:39,519 - INFO - Connected to ClickHouse database.
2025-03-24 15:21:39,867 - INFO - Final data inserted successfully into clickhouse for table test1
2025-03-24 15:21:39,867 - INFO - Data processing pipeline for queries\test1.py completed successfully!
2025-03-24 15:21:39,875 - INFO - Starting data processing for queries\test2.py
2025-03-24 15:21:40,351 - INFO - Connected to ClickHouse database.
2025-03-24 15:21:40,839 - INFO - Connected to ClickHouse database.
2025-03-24 15:21:41,009 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 15:21:41,036 - INFO - Connected to MySQL database.
2025-03-24 15:21:41,037 - INFO - Client creds received
2025-03-24 15:21:41,947 - INFO - Query execution completed
2025-03-24 15:21:41,948 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 15:21:41,948 - INFO - MySQL connection closed.
2025-03-24 15:21:42,719 - INFO - Connected to ClickHouse database.
2025-03-24 15:21:43,047 - INFO - Final data inserted successfully into clickhouse for table test2
2025-03-24 15:21:43,047 - INFO - Data processing pipeline for queries\test2.py completed successfully!
2025-03-24 15:21:43,067 - INFO - Starting data processing for queries\test3.py
2025-03-24 15:21:43,557 - INFO - Connected to ClickHouse database.
2025-03-24 15:21:44,047 - INFO - Connected to ClickHouse database.
2025-03-24 15:21:44,267 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 15:21:44,296 - INFO - Connected to MySQL database.
2025-03-24 15:21:44,296 - INFO - Client creds received
2025-03-24 15:21:44,299 - INFO - Query execution completed
2025-03-24 15:21:44,301 - INFO - Data fetched successfully from 'bank_data' in 'AH' database.
2025-03-24 15:21:44,301 - INFO - MySQL connection closed.
2025-03-24 15:21:44,303 - ERROR - Error in processing queries\test3.py: name 'pd' is not defined
2025-03-24 15:21:44,303 - INFO - All query files processed successfully!
2025-03-24 15:23:24,590 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 15:23:24,591 - INFO - Starting data processing for queries\test1.py
2025-03-24 15:23:26,427 - INFO - Connected to ClickHouse database.
2025-03-24 15:23:26,909 - INFO - Connected to ClickHouse database.
2025-03-24 15:23:27,086 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 15:23:27,102 - INFO - Connected to MySQL database.
2025-03-24 15:23:27,103 - INFO - Client creds received
2025-03-24 15:23:28,817 - INFO - Query execution completed
2025-03-24 15:23:28,817 - INFO - Data fetched successfully from database.
2025-03-24 15:23:28,817 - INFO - MySQL connection closed.
2025-03-24 15:23:29,977 - INFO - Connected to ClickHouse database.
2025-03-24 15:23:30,318 - INFO - Final data inserted successfully into clickhouse for table test1
2025-03-24 15:23:30,318 - INFO - Data processing pipeline for queries\test1.py completed successfully!
2025-03-24 15:23:30,318 - INFO - Starting data processing for queries\test2.py
2025-03-24 15:23:30,927 - INFO - Connected to ClickHouse database.
2025-03-24 15:23:31,496 - INFO - Connected to ClickHouse database.
2025-03-24 15:23:31,669 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 15:23:31,691 - INFO - Connected to MySQL database.
2025-03-24 15:23:31,691 - INFO - Client creds received
2025-03-24 15:23:32,602 - INFO - Query execution completed
2025-03-24 15:23:32,604 - INFO - Data fetched successfully from database.
2025-03-24 15:23:32,604 - INFO - MySQL connection closed.
2025-03-24 15:23:33,269 - INFO - Connected to ClickHouse database.
2025-03-24 15:23:33,592 - INFO - Final data inserted successfully into clickhouse for table test2
2025-03-24 15:23:33,592 - INFO - Data processing pipeline for queries\test2.py completed successfully!
2025-03-24 15:23:33,627 - INFO - Starting data processing for queries\test3.py
2025-03-24 15:23:34,101 - INFO - Connected to ClickHouse database.
2025-03-24 15:23:34,577 - INFO - Connected to ClickHouse database.
2025-03-24 15:23:34,764 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 15:23:34,782 - INFO - Connected to MySQL database.
2025-03-24 15:23:34,783 - INFO - Client creds received
2025-03-24 15:23:34,785 - INFO - Query execution completed
2025-03-24 15:23:34,786 - INFO - Data fetched successfully from database.
2025-03-24 15:23:34,787 - INFO - MySQL connection closed.
2025-03-24 15:23:34,789 - ERROR - Error in processing queries\test3.py: name 'pd' is not defined
2025-03-24 15:23:34,789 - INFO - All query files processed successfully!
2025-03-24 15:25:04,251 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 15:25:04,253 - INFO - Starting data processing for queries\test1.py
2025-03-24 15:25:06,989 - INFO - Connected to ClickHouse database.
2025-03-24 15:25:07,590 - INFO - Connected to ClickHouse database.
2025-03-24 15:25:07,770 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 15:25:07,790 - INFO - Connected to MySQL database.
2025-03-24 15:25:07,791 - INFO - Client creds received
2025-03-24 15:25:09,426 - INFO - Query execution completed
2025-03-24 15:25:09,427 - INFO - Data fetched successfully from database.
2025-03-24 15:25:09,427 - INFO - MySQL connection closed.
2025-03-24 15:25:10,249 - INFO - Connected to ClickHouse database.
2025-03-24 15:25:10,924 - INFO - Final data inserted successfully into clickhouse for table test1
2025-03-24 15:25:10,924 - INFO - Data processing pipeline for queries\test1.py completed successfully!
2025-03-24 15:25:10,927 - INFO - Starting data processing for queries\test2.py
2025-03-24 15:25:11,556 - INFO - Connected to ClickHouse database.
2025-03-24 15:25:12,039 - INFO - Connected to ClickHouse database.
2025-03-24 15:25:12,217 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 15:25:12,236 - INFO - Connected to MySQL database.
2025-03-24 15:25:12,237 - INFO - Client creds received
2025-03-24 15:25:13,158 - INFO - Query execution completed
2025-03-24 15:25:13,158 - INFO - Data fetched successfully from database.
2025-03-24 15:25:13,158 - INFO - MySQL connection closed.
2025-03-24 15:25:13,797 - INFO - Connected to ClickHouse database.
2025-03-24 15:25:14,116 - INFO - Final data inserted successfully into clickhouse for table test2
2025-03-24 15:25:14,117 - INFO - Data processing pipeline for queries\test2.py completed successfully!
2025-03-24 15:25:14,135 - INFO - Starting data processing for queries\test3.py
2025-03-24 15:25:14,618 - INFO - Connected to ClickHouse database.
2025-03-24 15:25:15,098 - INFO - Connected to ClickHouse database.
2025-03-24 15:25:15,287 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 15:25:15,300 - INFO - Connected to MySQL database.
2025-03-24 15:25:15,301 - INFO - Client creds received
2025-03-24 15:25:15,303 - INFO - Query execution completed
2025-03-24 15:25:15,305 - INFO - Data fetched successfully from database.
2025-03-24 15:25:15,306 - INFO - MySQL connection closed.
2025-03-24 15:25:15,799 - INFO - Connected to ClickHouse database.
2025-03-24 15:25:15,952 - ERROR - Error serializing column `image_x` into data type `String`
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Lib\site-packages\clickhouse_connect\driver\transform.py", line 99, in chunk_gen
    col_type.write_column(data, output, context)
  File "C:\Users\HP\anaconda3\Lib\site-packages\clickhouse_connect\datatypes\base.py", line 214, in write_column
    self.write_column_data(column, dest, ctx)
  File "C:\Users\HP\anaconda3\Lib\site-packages\clickhouse_connect\datatypes\base.py", line 229, in write_column_data
    self._write_column_binary(column, dest, ctx)
  File "C:\Users\HP\anaconda3\Lib\site-packages\clickhouse_connect\datatypes\string.py", line 50, in _write_column_binary
    handle_error(data_conv.write_str_col(column, self.nullable, encoding, dest), ctx)
  File "C:\Users\HP\anaconda3\Lib\site-packages\clickhouse_connect\driver\errors.py", line 17, in handle_error
    raise DataError(msg)
clickhouse_connect.driver.exceptions.DataError: Invalid None value in non-Nullable column, column name: `image_x`
2025-03-24 15:25:16,106 - ERROR - Error in inserting data: Invalid None value in non-Nullable column, column name: `image_x`
2025-03-24 15:25:16,107 - ERROR - Error in processing queries\test3.py: Invalid None value in non-Nullable column, column name: `image_x`
2025-03-24 15:25:16,107 - INFO - All query files processed successfully!
2025-03-24 15:36:19,773 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 15:36:19,775 - INFO - Starting data processing for queries\test1.py
2025-03-24 15:36:24,131 - INFO - Connected to ClickHouse database.
2025-03-24 15:36:24,690 - INFO - Connected to ClickHouse database.
2025-03-24 15:36:24,881 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 15:36:24,896 - INFO - Connected to MySQL database.
2025-03-24 15:36:24,897 - INFO - Client creds received
2025-03-24 15:36:27,228 - INFO - Query execution completed
2025-03-24 15:36:27,231 - INFO - Data fetched successfully from database.
2025-03-24 15:36:27,232 - INFO - MySQL connection closed.
2025-03-24 15:36:27,802 - INFO - Connected to ClickHouse database.
2025-03-24 15:36:28,953 - INFO - Final data inserted successfully into clickhouse for table test1
2025-03-24 15:36:28,953 - INFO - Data processing pipeline for queries\test1.py completed successfully!
2025-03-24 15:36:28,957 - INFO - Starting data processing for queries\test2.py
2025-03-24 15:36:29,444 - INFO - Connected to ClickHouse database.
2025-03-24 15:36:29,924 - INFO - Connected to ClickHouse database.
2025-03-24 15:36:30,101 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 15:36:30,104 - INFO - Connected to MySQL database.
2025-03-24 15:36:30,104 - INFO - Client creds received
2025-03-24 15:36:31,318 - INFO - Query execution completed
2025-03-24 15:36:31,321 - INFO - Data fetched successfully from database.
2025-03-24 15:36:31,321 - INFO - MySQL connection closed.
2025-03-24 15:36:32,114 - INFO - Connected to ClickHouse database.
2025-03-24 15:36:32,431 - INFO - Final data inserted successfully into clickhouse for table test2
2025-03-24 15:36:32,431 - INFO - Data processing pipeline for queries\test2.py completed successfully!
2025-03-24 15:36:32,451 - INFO - Starting data processing for queries\test3.py
2025-03-24 15:36:32,933 - INFO - Connected to ClickHouse database.
2025-03-24 15:36:33,422 - INFO - Connected to ClickHouse database.
2025-03-24 15:36:33,663 - INFO - Table 'final_table' checked/created successfully in 'AH' database.
2025-03-24 15:36:33,681 - INFO - Connected to MySQL database.
2025-03-24 15:36:33,681 - INFO - Client creds received
2025-03-24 15:36:33,685 - INFO - Query execution completed
2025-03-24 15:36:33,687 - INFO - Data fetched successfully from database.
2025-03-24 15:36:33,687 - INFO - MySQL connection closed.
2025-03-24 15:36:34,183 - INFO - Connected to ClickHouse database.
2025-03-24 15:36:34,588 - INFO - Final data inserted successfully into clickhouse for table product
2025-03-24 15:36:34,589 - INFO - Data processing pipeline for queries\test3.py completed successfully!
2025-03-24 15:36:34,590 - INFO - All query files processed successfully!
2025-03-24 18:13:33,748 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 18:13:33,748 - INFO - Starting the pipeline for queries\test1.py
2025-03-24 18:13:59,505 - INFO - Starting the data processing pipeline for all query files.
2025-03-24 18:13:59,508 - INFO - Starting the pipeline for queries\test1.py
2025-03-24 18:14:34,962 - INFO - Connected to ClickHouse database.
2025-03-24 18:14:36,091 - INFO - Connected to ClickHouse database.
2025-03-24 18:14:36,283 - INFO - Table test1 checked/created successfully in 'AH' database.
2025-03-24 18:14:36,296 - INFO - Connected to MySQL database.
2025-03-24 18:14:36,296 - INFO - Client creds received
2025-03-24 18:14:38,493 - INFO - Query execution completed
2025-03-24 18:14:38,509 - INFO - Data fetched successfully from database.
2025-03-24 18:14:38,509 - INFO - 854 fetched
2025-03-24 18:14:38,511 - INFO - MySQL connection closed.
2025-03-24 18:14:39,568 - INFO - Connected to ClickHouse database.
2025-03-24 18:14:40,524 - INFO - Final data inserted successfully into clickhouse for table test1
2025-03-24 18:14:40,524 - INFO - Data processing pipeline for queries\test1.py completed successfully!
2025-03-24 18:14:40,533 - INFO - Starting the pipeline for queries\test2.py
2025-03-24 18:14:41,040 - INFO - Connected to ClickHouse database.
2025-03-24 18:14:41,542 - INFO - Connected to ClickHouse database.
2025-03-24 18:14:41,732 - INFO - Table test2 checked/created successfully in 'AH' database.
2025-03-24 18:14:41,736 - INFO - Connected to MySQL database.
2025-03-24 18:14:41,736 - INFO - Client creds received
2025-03-24 18:14:42,807 - INFO - Query execution completed
2025-03-24 18:14:42,808 - INFO - Data fetched successfully from database.
2025-03-24 18:14:42,808 - INFO - 122 fetched
2025-03-24 18:14:42,810 - INFO - MySQL connection closed.
2025-03-24 18:14:43,475 - INFO - Connected to ClickHouse database.
2025-03-24 18:14:43,881 - INFO - Final data inserted successfully into clickhouse for table test2
2025-03-24 18:14:43,881 - INFO - Data processing pipeline for queries\test2.py completed successfully!
2025-03-24 18:14:43,881 - INFO - Starting the pipeline for queries\test3.py
2025-03-24 18:14:44,392 - INFO - Connected to ClickHouse database.
2025-03-24 18:14:44,904 - INFO - Connected to ClickHouse database.
2025-03-24 18:14:45,090 - INFO - Table product checked/created successfully in 'AH' database.
2025-03-24 18:14:45,106 - INFO - Connected to MySQL database.
2025-03-24 18:14:45,107 - INFO - Client creds received
2025-03-24 18:14:45,107 - INFO - Query execution completed
2025-03-24 18:14:45,114 - INFO - Data fetched successfully from database.
2025-03-24 18:14:45,115 - INFO - 5 fetched
2025-03-24 18:14:45,117 - INFO - MySQL connection closed.
2025-03-24 18:14:45,651 - INFO - Connected to ClickHouse database.
2025-03-24 18:14:46,053 - INFO - Final data inserted successfully into clickhouse for table product
2025-03-24 18:14:46,053 - INFO - Data processing pipeline for queries\test3.py completed successfully!
2025-03-24 18:14:46,057 - INFO - All query files processed successfully!
2025-03-26 14:56:29,598 - INFO - Starting the data processing pipeline for all query files.
2025-03-26 14:56:29,619 - INFO - Starting the pipeline for queries\test1.py
2025-03-26 14:56:31,915 - INFO - Connected to ClickHouse database.
2025-03-26 14:56:32,550 - INFO - Connected to ClickHouse database.
2025-03-26 14:56:32,762 - INFO - Table 'test1' checked/created successfully in the database.
2025-03-26 14:56:32,861 - INFO - Connected to MySQL database.
2025-03-26 14:56:32,861 - INFO - Client creds received
2025-03-26 14:56:35,186 - INFO - Query execution completed
2025-03-26 14:56:35,193 - INFO - Data fetched successfully from database.
2025-03-26 14:56:35,193 - INFO - 854 rows fetched
2025-03-26 14:56:35,195 - INFO - MySQL connection closed.
2025-03-26 14:56:36,240 - INFO - Connected to ClickHouse database.
2025-03-26 14:56:36,819 - INFO - Final data inserted successfully into clickhouse for table test1
2025-03-26 14:56:36,821 - INFO - Data processing pipeline for queries\test1.py completed successfully!
2025-03-26 14:56:36,829 - INFO - Starting the pipeline for queries\test2.py
2025-03-26 14:56:37,538 - INFO - Connected to ClickHouse database.
2025-03-26 14:56:38,361 - INFO - Connected to ClickHouse database.
2025-03-26 14:56:38,588 - INFO - Table 'test2' checked/created successfully in the database.
2025-03-26 14:56:38,603 - INFO - Connected to MySQL database.
2025-03-26 14:56:38,603 - INFO - Client creds received
2025-03-26 14:56:39,801 - INFO - Query execution completed
2025-03-26 14:56:39,803 - INFO - Data fetched successfully from database.
2025-03-26 14:56:39,803 - INFO - 122 rows fetched
2025-03-26 14:56:39,803 - INFO - MySQL connection closed.
2025-03-26 14:56:41,401 - INFO - Connected to ClickHouse database.
2025-03-26 14:56:42,103 - INFO - Final data inserted successfully into clickhouse for table test2
2025-03-26 14:56:42,105 - INFO - Data processing pipeline for queries\test2.py completed successfully!
2025-03-26 14:56:42,107 - INFO - Starting the pipeline for queries\test3.py
2025-03-26 14:56:42,802 - INFO - Connected to ClickHouse database.
2025-03-26 14:56:43,448 - INFO - Connected to ClickHouse database.
2025-03-26 14:56:43,662 - INFO - Table 'product' checked/created successfully in the database.
2025-03-26 14:56:43,665 - INFO - Connected to MySQL database.
2025-03-26 14:56:43,665 - INFO - Client creds received
2025-03-26 14:56:43,703 - INFO - Query execution completed
2025-03-26 14:56:43,706 - INFO - Data fetched successfully from database.
2025-03-26 14:56:43,710 - INFO - 5 rows fetched
2025-03-26 14:56:43,710 - INFO - MySQL connection closed.
2025-03-26 14:56:44,631 - INFO - Connected to ClickHouse database.
2025-03-26 14:56:45,101 - INFO - Final data inserted successfully into clickhouse for table product
2025-03-26 14:56:45,101 - INFO - Data processing pipeline for queries\test3.py completed successfully!
2025-03-26 14:56:45,101 - INFO - All query files processed successfully!
2025-03-27 13:21:00,266 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 13:21:00,267 - INFO - Starting the pipeline for queries\test1.py
2025-03-27 13:21:05,577 - INFO - Connected to ClickHouse database.
2025-03-27 13:21:07,421 - INFO - Connected to ClickHouse database.
2025-03-27 13:21:07,609 - INFO - Table 'test1' checked/created successfully in the database.
2025-03-27 13:21:07,620 - INFO - Connected to MySQL database.
2025-03-27 13:21:07,620 - INFO - Client creds received
2025-03-27 13:21:09,919 - INFO - Query execution completed
2025-03-27 13:21:09,933 - INFO - Data fetched successfully from database.
2025-03-27 13:21:09,934 - INFO - 854 rows fetched
2025-03-27 13:21:09,934 - INFO - MySQL connection closed.
2025-03-27 13:21:14,221 - INFO - Connected to ClickHouse database.
2025-03-27 13:21:14,643 - INFO - Final data inserted successfully into clickhouse for table test1
2025-03-27 13:21:14,645 - INFO - Data processing pipeline for queries\test1.py completed successfully!
2025-03-27 13:21:14,654 - INFO - Starting the pipeline for queries\test2.py
2025-03-27 13:21:16,122 - INFO - Connected to ClickHouse database.
2025-03-27 13:21:22,912 - INFO - Connected to ClickHouse database.
2025-03-27 13:21:23,367 - INFO - Table 'test2' checked/created successfully in the database.
2025-03-27 13:21:23,372 - INFO - Connected to MySQL database.
2025-03-27 13:21:23,372 - INFO - Client creds received
2025-03-27 13:21:24,544 - INFO - Query execution completed
2025-03-27 13:21:24,546 - INFO - Data fetched successfully from database.
2025-03-27 13:21:24,547 - INFO - 122 rows fetched
2025-03-27 13:21:24,547 - INFO - MySQL connection closed.
2025-03-27 13:21:28,953 - INFO - Connected to ClickHouse database.
2025-03-27 13:21:29,342 - INFO - Final data inserted successfully into clickhouse for table test2
2025-03-27 13:21:29,344 - INFO - Data processing pipeline for queries\test2.py completed successfully!
2025-03-27 13:21:29,346 - INFO - Starting the pipeline for queries\test3.py
2025-03-27 13:21:30,457 - INFO - Connected to ClickHouse database.
2025-03-27 13:21:31,931 - INFO - Connected to ClickHouse database.
2025-03-27 13:21:32,108 - INFO - Table 'product' checked/created successfully in the database.
2025-03-27 13:21:32,133 - INFO - Connected to MySQL database.
2025-03-27 13:21:32,133 - INFO - Client creds received
2025-03-27 13:21:32,136 - INFO - Query execution completed
2025-03-27 13:21:32,147 - INFO - Data fetched successfully from database.
2025-03-27 13:21:32,148 - INFO - 5 rows fetched
2025-03-27 13:21:32,149 - INFO - MySQL connection closed.
2025-03-27 13:21:33,510 - INFO - Connected to ClickHouse database.
2025-03-27 13:21:33,890 - INFO - Final data inserted successfully into clickhouse for table product
2025-03-27 13:21:33,891 - INFO - Data processing pipeline for queries\test3.py completed successfully!
2025-03-27 13:21:33,891 - INFO - All query files processed successfully!
2025-03-27 13:34:09,217 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 13:34:09,220 - INFO - Starting the pipeline for queries\test1.py
2025-03-27 13:34:11,851 - INFO - Connected to ClickHouse database.
2025-03-27 13:34:12,602 - INFO - Connected to ClickHouse database.
2025-03-27 13:34:12,922 - INFO - Table 'test1' checked/created successfully in the database.
2025-03-27 13:34:12,926 - INFO - Connected to MySQL database.
2025-03-27 13:34:12,927 - INFO - Client creds received
2025-03-27 13:34:15,267 - INFO - Query execution completed
2025-03-27 13:34:15,270 - INFO - Data fetched successfully from database.
2025-03-27 13:34:15,270 - INFO - 854 rows fetched
2025-03-27 13:34:15,271 - INFO - MySQL connection closed.
2025-03-27 13:34:16,432 - INFO - Connected to ClickHouse database.
2025-03-27 13:34:16,898 - INFO - Final data inserted successfully into clickhouse for table test1
2025-03-27 13:34:16,899 - INFO - Data processing pipeline for queries\test1.py completed successfully!
2025-03-27 13:34:16,900 - INFO - Starting the pipeline for queries\test2.py
2025-03-27 13:34:17,587 - INFO - Connected to ClickHouse database.
2025-03-27 13:34:18,131 - INFO - Connected to ClickHouse database.
2025-03-27 13:34:18,385 - INFO - Table 'test2' checked/created successfully in the database.
2025-03-27 13:34:18,388 - INFO - Connected to MySQL database.
2025-03-27 13:34:18,388 - INFO - Client creds received
2025-03-27 13:34:19,546 - INFO - Query execution completed
2025-03-27 13:34:19,548 - INFO - Data fetched successfully from database.
2025-03-27 13:34:19,548 - INFO - 122 rows fetched
2025-03-27 13:34:19,549 - INFO - MySQL connection closed.
2025-03-27 13:34:20,572 - INFO - Connected to ClickHouse database.
2025-03-27 13:34:21,150 - INFO - Final data inserted successfully into clickhouse for table test2
2025-03-27 13:34:21,151 - INFO - Data processing pipeline for queries\test2.py completed successfully!
2025-03-27 13:34:21,152 - INFO - Starting the pipeline for queries\test3.py
2025-03-27 13:34:21,713 - INFO - Connected to ClickHouse database.
2025-03-27 13:34:22,327 - INFO - Connected to ClickHouse database.
2025-03-27 13:34:22,592 - INFO - Table 'product' checked/created successfully in the database.
2025-03-27 13:34:22,613 - INFO - Connected to MySQL database.
2025-03-27 13:34:22,614 - INFO - Client creds received
2025-03-27 13:34:22,617 - INFO - Query execution completed
2025-03-27 13:34:22,619 - INFO - Data fetched successfully from database.
2025-03-27 13:34:22,620 - INFO - 5 rows fetched
2025-03-27 13:34:22,621 - INFO - MySQL connection closed.
2025-03-27 13:34:23,267 - INFO - Connected to ClickHouse database.
2025-03-27 13:34:24,107 - INFO - Final data inserted successfully into clickhouse for table product
2025-03-27 13:34:24,108 - INFO - Data processing pipeline for queries\test3.py completed successfully!
2025-03-27 13:34:24,108 - INFO - All query files processed successfully!
2025-03-27 14:04:37,419 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 14:04:37,421 - INFO - Starting the pipeline for queries\test1.py
2025-03-27 14:04:41,856 - INFO - Connected to ClickHouse database.
2025-03-27 14:04:43,043 - INFO - Connected to ClickHouse database.
2025-03-27 14:04:43,292 - INFO - Table 'test1' checked/created successfully in the database.
2025-03-27 14:04:43,298 - INFO - Connected to MySQL database.
2025-03-27 14:04:43,299 - INFO - Client creds received
2025-03-27 14:04:45,383 - INFO - Query execution completed
2025-03-27 14:04:45,386 - INFO - Data fetched successfully from database.
2025-03-27 14:04:45,387 - INFO - 854 rows fetched
2025-03-27 14:04:45,387 - INFO - MySQL connection closed.
2025-03-27 14:04:47,401 - INFO - Connected to ClickHouse database.
2025-03-27 14:04:47,846 - INFO - Final data inserted successfully into clickhouse for table test1
2025-03-27 14:04:47,846 - INFO - Data processing pipeline for queries\test1.py completed successfully!
2025-03-27 14:04:47,848 - INFO - Starting the pipeline for queries\test2.py
2025-03-27 14:04:49,947 - INFO - Connected to ClickHouse database.
2025-03-27 14:04:52,174 - INFO - Connected to ClickHouse database.
2025-03-27 14:04:52,406 - INFO - Table 'test2' checked/created successfully in the database.
2025-03-27 14:04:52,411 - INFO - Connected to MySQL database.
2025-03-27 14:04:52,412 - INFO - Client creds received
2025-03-27 14:04:53,579 - INFO - Query execution completed
2025-03-27 14:04:53,580 - INFO - Data fetched successfully from database.
2025-03-27 14:04:53,581 - INFO - 122 rows fetched
2025-03-27 14:04:53,581 - INFO - MySQL connection closed.
2025-03-27 14:05:01,585 - INFO - Connected to ClickHouse database.
2025-03-27 14:05:02,181 - INFO - Final data inserted successfully into clickhouse for table test2
2025-03-27 14:05:02,182 - INFO - Data processing pipeline for queries\test2.py completed successfully!
2025-03-27 14:05:02,184 - INFO - Starting the pipeline for queries\test3.py
2025-03-27 14:05:04,189 - INFO - Connected to ClickHouse database.
2025-03-27 14:05:06,721 - INFO - Connected to ClickHouse database.
2025-03-27 14:05:06,963 - INFO - Table 'product' checked/created successfully in the database.
2025-03-27 14:05:06,968 - INFO - Connected to MySQL database.
2025-03-27 14:05:06,970 - INFO - Client creds received
2025-03-27 14:05:06,973 - INFO - Query execution completed
2025-03-27 14:05:06,975 - INFO - Data fetched successfully from database.
2025-03-27 14:05:06,975 - INFO - 5 rows fetched
2025-03-27 14:05:06,977 - INFO - MySQL connection closed.
2025-03-27 14:05:08,472 - INFO - Connected to ClickHouse database.
2025-03-27 14:05:08,890 - INFO - Final data inserted successfully into clickhouse for table product
2025-03-27 14:05:08,891 - INFO - Data processing pipeline for queries\test3.py completed successfully!
2025-03-27 14:05:08,891 - INFO - All query files processed successfully!
2025-03-27 14:08:28,215 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 14:08:28,217 - INFO - Starting the pipeline for queries\test1.py
2025-03-27 14:08:32,518 - INFO - Connected to ClickHouse database.
2025-03-27 14:08:33,160 - INFO - Connected to ClickHouse database.
2025-03-27 14:08:33,380 - INFO - Table 'test1' checked/created successfully in the database.
2025-03-27 14:08:33,386 - INFO - Connected to MySQL database.
2025-03-27 14:08:33,387 - INFO - Client creds received
2025-03-27 14:08:35,372 - INFO - Query execution completed
2025-03-27 14:08:35,376 - INFO - Data fetched successfully from database.
2025-03-27 14:08:35,376 - INFO - 854 rows fetched
2025-03-27 14:08:35,378 - INFO - MySQL connection closed.
2025-03-27 14:08:36,724 - INFO - Connected to ClickHouse database.
2025-03-27 14:08:37,136 - INFO - Final data inserted successfully into clickhouse for table test1
2025-03-27 14:08:37,136 - INFO - Data processing pipeline for queries\test1.py completed successfully!
2025-03-27 14:08:37,138 - INFO - Starting the pipeline for queries\test2.py
2025-03-27 14:08:38,636 - INFO - Connected to ClickHouse database.
2025-03-27 14:08:40,227 - INFO - Connected to ClickHouse database.
2025-03-27 14:08:40,452 - INFO - Table 'test2' checked/created successfully in the database.
2025-03-27 14:08:40,457 - INFO - Connected to MySQL database.
2025-03-27 14:08:40,457 - INFO - Client creds received
2025-03-27 14:08:41,571 - INFO - Query execution completed
2025-03-27 14:08:41,572 - INFO - Data fetched successfully from database.
2025-03-27 14:08:41,573 - INFO - 122 rows fetched
2025-03-27 14:08:41,573 - INFO - MySQL connection closed.
2025-03-27 14:08:47,242 - INFO - Connected to ClickHouse database.
2025-03-27 14:08:47,667 - INFO - Final data inserted successfully into clickhouse for table test2
2025-03-27 14:08:47,667 - INFO - Data processing pipeline for queries\test2.py completed successfully!
2025-03-27 14:08:47,669 - INFO - Starting the pipeline for queries\test3.py
2025-03-27 14:08:49,705 - INFO - Connected to ClickHouse database.
2025-03-27 14:08:51,277 - INFO - Connected to ClickHouse database.
2025-03-27 14:08:51,702 - INFO - Table 'product' checked/created successfully in the database.
2025-03-27 14:08:51,707 - INFO - Connected to MySQL database.
2025-03-27 14:08:51,708 - INFO - Client creds received
2025-03-27 14:08:51,712 - INFO - Query execution completed
2025-03-27 14:08:51,715 - INFO - Data fetched successfully from database.
2025-03-27 14:08:51,715 - INFO - 5 rows fetched
2025-03-27 14:08:51,718 - INFO - MySQL connection closed.
2025-03-27 14:08:55,112 - INFO - Connected to ClickHouse database.
2025-03-27 14:08:55,783 - INFO - Final data inserted successfully into clickhouse for table product
2025-03-27 14:08:55,783 - INFO - Data processing pipeline for queries\test3.py completed successfully!
2025-03-27 14:08:55,784 - INFO - All query files processed successfully!
2025-03-27 16:11:08,519 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 16:11:08,536 - INFO - Starting the pipeline for queries\test1.py
2025-03-27 16:11:12,671 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000018DCAE2E060>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /?
2025-03-27 16:11:16,747 - WARNING - Unexpected Http Driver Exception
2025-03-27 16:11:16,747 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: /? (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000018DCAE2E090>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) executing HTTP request attempt 1 (https://localhost:8443)
2025-03-27 16:11:16,747 - ERROR - Error in processing queries\test1.py: Error HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: /? (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000018DCAE2E090>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) executing HTTP request attempt 1 (https://localhost:8443)
2025-03-27 16:11:16,747 - INFO - Starting the pipeline for queries\test2.py
2025-03-27 16:11:20,872 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000018DCAE2F3B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /?
2025-03-27 16:11:24,975 - WARNING - Unexpected Http Driver Exception
2025-03-27 16:11:24,975 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: /? (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000018DCAE2F500>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) executing HTTP request attempt 1 (https://localhost:8443)
2025-03-27 16:11:24,975 - ERROR - Error in processing queries\test2.py: Error HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: /? (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000018DCAE2F500>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) executing HTTP request attempt 1 (https://localhost:8443)
2025-03-27 16:11:24,975 - INFO - Starting the pipeline for queries\test3.py
2025-03-27 16:11:29,061 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000018DC92E9B80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /?
2025-03-27 16:11:33,103 - WARNING - Unexpected Http Driver Exception
2025-03-27 16:11:33,103 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: /? (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000018DCAC83800>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) executing HTTP request attempt 1 (https://localhost:8443)
2025-03-27 16:11:33,103 - ERROR - Error in processing queries\test3.py: Error HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: /? (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000018DCAC83800>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) executing HTTP request attempt 1 (https://localhost:8443)
2025-03-27 16:11:33,104 - INFO - All query files processed successfully!
2025-03-27 16:13:25,887 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 16:13:25,887 - INFO - Starting the pipeline for queries\test1.py
2025-03-27 16:13:29,977 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C57F935940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /?
2025-03-27 16:13:34,034 - WARNING - Unexpected Http Driver Exception
2025-03-27 16:13:34,034 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: /? (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C501B9E510>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) executing HTTP request attempt 1 (https://localhost:8443)
2025-03-27 16:13:34,034 - ERROR - Error in processing queries\test1.py: Error HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: /? (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C501B9E510>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) executing HTTP request attempt 1 (https://localhost:8443)
2025-03-27 16:13:34,034 - INFO - Starting the pipeline for queries\test2.py
2025-03-27 16:13:38,119 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C501B9F3B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /?
2025-03-27 16:14:24,268 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 16:14:24,269 - INFO - Starting the pipeline for queries\test1.py
2025-03-27 16:14:28,358 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000119C5FF5700>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /?
2025-03-27 16:14:32,456 - WARNING - Unexpected Http Driver Exception
2025-03-27 16:14:32,456 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: /? (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000119C820E7B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) executing HTTP request attempt 1 (https://localhost:8443)
2025-03-27 16:14:32,456 - ERROR - Error in processing queries\test1.py: Error HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: /? (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000119C820E7B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) executing HTTP request attempt 1 (https://localhost:8443)
2025-03-27 16:14:32,456 - INFO - Starting the pipeline for queries\test2.py
2025-03-27 16:14:36,521 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000119C820F9B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /?
2025-03-27 16:14:40,599 - WARNING - Unexpected Http Driver Exception
2025-03-27 16:14:40,600 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: /? (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000119C820FB00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) executing HTTP request attempt 1 (https://localhost:8443)
2025-03-27 16:14:40,600 - ERROR - Error in processing queries\test2.py: Error HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: /? (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000119C820FB00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) executing HTTP request attempt 1 (https://localhost:8443)
2025-03-27 16:14:40,601 - INFO - Starting the pipeline for queries\test3.py
2025-03-27 16:14:44,702 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000119C820FEC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /?
2025-03-27 16:14:48,827 - WARNING - Unexpected Http Driver Exception
2025-03-27 16:14:48,827 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: /? (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000119C5CF5220>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) executing HTTP request attempt 1 (https://localhost:8443)
2025-03-27 16:14:48,827 - ERROR - Error in processing queries\test3.py: Error HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: /? (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000119C5CF5220>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) executing HTTP request attempt 1 (https://localhost:8443)
2025-03-27 16:14:48,827 - INFO - All query files processed successfully!
2025-03-27 16:16:21,986 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 16:16:21,986 - INFO - Starting the pipeline for queries\test1.py
2025-03-27 16:16:25,059 - INFO - Connected to ClickHouse database.
2025-03-27 16:16:25,997 - INFO - Connected to ClickHouse database.
2025-03-27 16:16:26,232 - INFO - Table 'test1' checked/created successfully in the database.
2025-03-27 16:16:26,251 - INFO - Connected to MySQL database.
2025-03-27 16:16:26,251 - INFO - Client creds received
2025-03-27 16:16:27,967 - INFO - Query execution completed
2025-03-27 16:16:27,982 - INFO - Data fetched successfully from database.
2025-03-27 16:16:27,982 - INFO - 854 rows fetched
2025-03-27 16:16:27,982 - INFO - MySQL connection closed.
2025-03-27 16:16:29,248 - INFO - Connected to ClickHouse database.
2025-03-27 16:16:30,014 - INFO - Final data inserted successfully into clickhouse for table test1
2025-03-27 16:16:30,030 - INFO - Data processing pipeline for queries\test1.py completed successfully!
2025-03-27 16:16:30,037 - INFO - Starting the pipeline for queries\test2.py
2025-03-27 16:16:31,453 - INFO - Connected to ClickHouse database.
2025-03-27 16:16:32,843 - INFO - Connected to ClickHouse database.
2025-03-27 16:16:33,137 - INFO - Table 'test2' checked/created successfully in the database.
2025-03-27 16:16:33,155 - INFO - Connected to MySQL database.
2025-03-27 16:16:33,156 - INFO - Client creds received
2025-03-27 16:16:34,033 - INFO - Query execution completed
2025-03-27 16:16:34,033 - INFO - Data fetched successfully from database.
2025-03-27 16:16:34,033 - INFO - 122 rows fetched
2025-03-27 16:16:34,033 - INFO - MySQL connection closed.
2025-03-27 16:16:35,052 - INFO - Connected to ClickHouse database.
2025-03-27 16:16:35,626 - INFO - Final data inserted successfully into clickhouse for table test2
2025-03-27 16:16:35,627 - INFO - Data processing pipeline for queries\test2.py completed successfully!
2025-03-27 16:16:35,628 - INFO - Starting the pipeline for queries\test3.py
2025-03-27 16:16:36,486 - INFO - Connected to ClickHouse database.
2025-03-27 16:16:37,298 - INFO - Connected to ClickHouse database.
2025-03-27 16:16:37,609 - INFO - Table 'product' checked/created successfully in the database.
2025-03-27 16:16:37,624 - INFO - Connected to MySQL database.
2025-03-27 16:16:37,625 - INFO - Client creds received
2025-03-27 16:16:37,627 - INFO - Query execution completed
2025-03-27 16:16:37,631 - INFO - Data fetched successfully from database.
2025-03-27 16:16:37,632 - INFO - 5 rows fetched
2025-03-27 16:16:37,632 - INFO - MySQL connection closed.
2025-03-27 16:16:38,423 - INFO - Connected to ClickHouse database.
2025-03-27 16:16:38,908 - INFO - Final data inserted successfully into clickhouse for table product
2025-03-27 16:16:38,909 - INFO - Data processing pipeline for queries\test3.py completed successfully!
2025-03-27 16:16:38,910 - INFO - All query files processed successfully!
2025-03-27 18:57:09,790 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 18:57:09,791 - INFO - Starting data processing for queries\test1.py
2025-03-27 18:58:19,918 - ERROR - Failed to connect to ClickHouse: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 18:58:19,918 - ERROR - Error in processing queries\test1.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 18:58:19,923 - INFO - Starting data processing for queries\test2.py
2025-03-27 18:58:20,316 - ERROR - Failed to connect to ClickHouse: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 18:58:20,316 - ERROR - Error in processing queries\test2.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 18:58:20,332 - INFO - Starting data processing for queries\test3.py
2025-03-27 18:58:20,922 - ERROR - Failed to connect to ClickHouse: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 18:58:20,923 - ERROR - Error in processing queries\test3.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 18:58:20,925 - INFO - All query files processed successfully!
2025-03-27 18:58:47,377 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 18:58:47,380 - INFO - Starting data processing for queries\test1.py
2025-03-27 18:58:52,461 - ERROR - Failed to connect to ClickHouse: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 18:58:52,465 - ERROR - Error in processing queries\test1.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 18:58:52,467 - INFO - Starting data processing for queries\test2.py
2025-03-27 18:58:53,252 - ERROR - Failed to connect to ClickHouse: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 18:58:53,252 - ERROR - Error in processing queries\test2.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 18:58:53,256 - INFO - Starting data processing for queries\test3.py
2025-03-27 18:58:53,612 - ERROR - Failed to connect to ClickHouse: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 18:58:53,612 - ERROR - Error in processing queries\test3.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 18:58:53,614 - INFO - All query files processed successfully!
2025-03-27 18:59:27,732 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 18:59:27,737 - INFO - Starting data processing for queries\test1.py
2025-03-27 18:59:31,194 - ERROR - Failed to connect to ClickHouse: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 18:59:31,194 - ERROR - Error in processing queries\test1.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 18:59:31,202 - INFO - Starting data processing for queries\test2.py
2025-03-27 18:59:32,797 - ERROR - Failed to connect to ClickHouse: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 18:59:32,797 - ERROR - Error in processing queries\test2.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 18:59:32,800 - INFO - Starting data processing for queries\test3.py
2025-03-27 18:59:33,429 - ERROR - Failed to connect to ClickHouse: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 18:59:33,429 - ERROR - Error in processing queries\test3.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 18:59:33,432 - INFO - All query files processed successfully!
2025-03-27 19:00:17,639 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 19:00:17,641 - INFO - Starting data processing for queries\test1.py
2025-03-27 19:00:22,025 - ERROR - Failed to connect to ClickHouse: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 19:00:22,025 - ERROR - Error in processing queries\test1.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 19:00:22,029 - INFO - Starting data processing for queries\test2.py
2025-03-27 19:00:23,004 - ERROR - Failed to connect to ClickHouse: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 19:00:23,006 - ERROR - Error in processing queries\test2.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 19:00:23,008 - INFO - Starting data processing for queries\test3.py
2025-03-27 19:00:24,761 - ERROR - Failed to connect to ClickHouse: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 19:00:24,770 - ERROR - Error in processing queries\test3.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 19:00:24,771 - INFO - All query files processed successfully!
2025-03-27 22:46:11,776 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 22:46:11,776 - INFO - Starting data processing for queries\test1.py
2025-03-27 22:48:27,478 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 22:48:27,480 - INFO - Starting data processing for queries\test1.py
2025-03-27 22:48:34,412 - ERROR - Failed to connect to ClickHouse: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 22:48:34,421 - ERROR - Error in processing queries\test1.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 22:48:34,421 - INFO - Starting data processing for queries\test2.py
2025-03-27 22:48:34,718 - ERROR - Failed to connect to ClickHouse: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 22:48:34,718 - ERROR - Error in processing queries\test2.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 22:48:34,725 - INFO - Starting data processing for queries\test3.py
2025-03-27 22:48:35,040 - ERROR - Failed to connect to ClickHouse: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 22:48:35,040 - ERROR - Error in processing queries\test3.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 22:48:35,040 - INFO - All query files processed successfully!
2025-03-27 22:49:36,252 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 22:49:36,252 - INFO - Starting data processing for queries\test1.py
2025-03-27 22:49:48,311 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000029F588C5E20>, 'Connection to di33kgplgc.germanywestcentral.azure.clickhouse.cloud timed out. (connect timeout=10)')': /?
2025-03-27 22:50:00,351 - WARNING - Unexpected Http Driver Exception
2025-03-27 22:50:00,351 - ERROR - Failed to connect to ClickHouse: Error HTTPConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8123): Max retries exceeded with url: /? (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000029F5A48E6F0>, 'Connection to di33kgplgc.germanywestcentral.azure.clickhouse.cloud timed out. (connect timeout=10)')) executing HTTP request attempt 1 (http://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8123)
2025-03-27 22:50:00,351 - ERROR - Error in processing queries\test1.py: Error HTTPConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8123): Max retries exceeded with url: /? (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000029F5A48E6F0>, 'Connection to di33kgplgc.germanywestcentral.azure.clickhouse.cloud timed out. (connect timeout=10)')) executing HTTP request attempt 1 (http://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8123)
2025-03-27 22:50:00,351 - INFO - Starting data processing for queries\test2.py
2025-03-27 22:50:11,674 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000029F5A48F9B0>, 'Connection to di33kgplgc.germanywestcentral.azure.clickhouse.cloud timed out. (connect timeout=10)')': /?
2025-03-27 22:50:23,141 - WARNING - Unexpected Http Driver Exception
2025-03-27 22:50:23,141 - ERROR - Failed to connect to ClickHouse: Error HTTPConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8123): Max retries exceeded with url: /? (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000029F5A48FBC0>, 'Connection to di33kgplgc.germanywestcentral.azure.clickhouse.cloud timed out. (connect timeout=10)')) executing HTTP request attempt 1 (http://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8123)
2025-03-27 22:50:23,141 - ERROR - Error in processing queries\test2.py: Error HTTPConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8123): Max retries exceeded with url: /? (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000029F5A48FBC0>, 'Connection to di33kgplgc.germanywestcentral.azure.clickhouse.cloud timed out. (connect timeout=10)')) executing HTTP request attempt 1 (http://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8123)
2025-03-27 22:50:23,141 - INFO - Starting data processing for queries\test3.py
2025-03-27 22:50:33,384 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000029F54E52F00>, 'Connection to di33kgplgc.germanywestcentral.azure.clickhouse.cloud timed out. (connect timeout=10)')': /?
2025-03-27 22:50:43,858 - WARNING - Unexpected Http Driver Exception
2025-03-27 22:50:43,859 - ERROR - Failed to connect to ClickHouse: Error HTTPConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8123): Max retries exceeded with url: /? (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000029F5A48E540>, 'Connection to di33kgplgc.germanywestcentral.azure.clickhouse.cloud timed out. (connect timeout=10)')) executing HTTP request attempt 1 (http://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8123)
2025-03-27 22:50:43,859 - ERROR - Error in processing queries\test3.py: Error HTTPConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8123): Max retries exceeded with url: /? (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000029F5A48E540>, 'Connection to di33kgplgc.germanywestcentral.azure.clickhouse.cloud timed out. (connect timeout=10)')) executing HTTP request attempt 1 (http://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8123)
2025-03-27 22:50:43,859 - INFO - All query files processed successfully!
2025-03-27 22:52:06,077 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 22:52:06,077 - INFO - Starting data processing for queries\test1.py
2025-03-27 22:52:13,551 - ERROR - Failed to connect to ClickHouse: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 22:52:13,554 - ERROR - Error in processing queries\test1.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 22:52:13,556 - INFO - Starting data processing for queries\test2.py
2025-03-27 22:52:15,395 - ERROR - Failed to connect to ClickHouse: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 22:52:15,397 - ERROR - Error in processing queries\test2.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 22:52:15,399 - INFO - Starting data processing for queries\test3.py
2025-03-27 22:52:17,020 - ERROR - Failed to connect to ClickHouse: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 22:52:17,020 - ERROR - Error in processing queries\test3.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 516
 Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.10.1.11464 (official build))

2025-03-27 22:52:17,025 - INFO - All query files processed successfully!
2025-03-27 22:54:45,580 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 22:54:45,580 - INFO - Starting data processing for queries\test1.py
2025-03-27 22:54:51,315 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-27 22:55:01,749 - WARNING - Unexpected Http Driver Exception
2025-03-27 22:55:01,749 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 22:55:01,752 - ERROR - Error in processing queries\test1.py: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 22:55:01,754 - INFO - Starting data processing for queries\test2.py
2025-03-27 22:55:04,929 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-27 22:55:06,598 - WARNING - Unexpected Http Driver Exception
2025-03-27 22:55:06,598 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 22:55:06,600 - ERROR - Error in processing queries\test2.py: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 22:55:06,601 - INFO - Starting data processing for queries\test3.py
2025-03-27 22:55:13,728 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-27 22:55:14,723 - WARNING - Unexpected Http Driver Exception
2025-03-27 22:55:14,723 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 2 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 22:55:14,723 - ERROR - Error in processing queries\test3.py: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 2 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 22:55:14,724 - INFO - All query files processed successfully!
2025-03-27 22:56:58,049 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 22:56:58,053 - INFO - Starting data processing for queries\test1.py
2025-03-27 22:57:04,378 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-27 22:57:11,887 - WARNING - Unexpected Http Driver Exception
2025-03-27 22:57:11,889 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 22:57:11,889 - ERROR - Error in processing queries\test1.py: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 22:57:11,889 - INFO - Starting data processing for queries\test2.py
2025-03-27 22:57:16,137 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-27 22:58:10,224 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 22:58:10,224 - INFO - Starting data processing for queries\test1.py
2025-03-27 22:58:28,461 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-27 22:58:39,009 - WARNING - Unexpected Http Driver Exception
2025-03-27 22:58:39,009 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 22:58:39,009 - ERROR - Error in processing queries\test1.py: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 22:58:39,013 - INFO - Starting data processing for queries\test2.py
2025-03-27 22:58:42,260 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-27 22:58:44,386 - WARNING - Unexpected Http Driver Exception
2025-03-27 22:58:44,386 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 22:58:44,386 - ERROR - Error in processing queries\test2.py: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 22:58:44,388 - INFO - Starting data processing for queries\test3.py
2025-03-27 22:58:46,320 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-27 22:58:53,151 - WARNING - Unexpected Http Driver Exception
2025-03-27 22:58:53,151 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 22:58:53,160 - ERROR - Error in processing queries\test3.py: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 22:58:53,160 - INFO - All query files processed successfully!
2025-03-27 22:59:05,634 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 22:59:05,637 - INFO - Starting data processing for queries\test1.py
2025-03-27 22:59:09,141 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-27 22:59:11,204 - WARNING - Unexpected Http Driver Exception
2025-03-27 22:59:11,204 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 22:59:11,204 - ERROR - Error in processing queries\test1.py: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 22:59:11,207 - INFO - Starting data processing for queries\test2.py
2025-03-27 22:59:12,592 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-27 22:59:26,430 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-27 22:59:29,494 - WARNING - Unexpected Http Driver Exception
2025-03-27 22:59:29,494 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 2 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 22:59:29,494 - ERROR - Error in processing queries\test2.py: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 2 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 22:59:29,497 - INFO - Starting data processing for queries\test3.py
2025-03-27 23:10:28,658 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 23:10:28,660 - INFO - Starting data processing for queries\test1.py
2025-03-27 23:10:32,080 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-27 23:10:35,232 - WARNING - Unexpected Http Driver Exception
2025-03-27 23:10:35,232 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 23:10:35,232 - ERROR - Error in processing queries\test1.py: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 23:10:35,234 - INFO - Starting data processing for queries\test2.py
2025-03-27 23:10:39,504 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-27 23:10:41,554 - WARNING - Unexpected Http Driver Exception
2025-03-27 23:10:41,554 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 23:10:41,556 - ERROR - Error in processing queries\test2.py: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 23:10:41,558 - INFO - Starting data processing for queries\test3.py
2025-03-27 23:10:44,407 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-27 23:10:45,784 - WARNING - Unexpected Http Driver Exception
2025-03-27 23:10:45,784 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 23:10:45,784 - ERROR - Error in processing queries\test3.py: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 23:10:45,784 - INFO - All query files processed successfully!
2025-03-27 23:19:49,921 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 23:19:49,940 - INFO - Starting data processing for queries\test1.py
2025-03-27 23:19:52,968 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-27 23:19:54,381 - WARNING - Unexpected Http Driver Exception
2025-03-27 23:19:54,381 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 23:19:54,381 - ERROR - Error in processing queries\test1.py: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 23:19:54,410 - INFO - Starting data processing for queries\test2.py
2025-03-27 23:19:56,763 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-27 23:20:00,645 - WARNING - Unexpected Http Driver Exception
2025-03-27 23:20:00,645 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 23:20:00,645 - ERROR - Error in processing queries\test2.py: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 23:20:00,651 - INFO - Starting data processing for queries\test3.py
2025-03-27 23:20:03,001 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /?
2025-03-27 23:20:05,237 - WARNING - Unexpected Http Driver Exception
2025-03-27 23:20:05,237 - ERROR - Failed to connect to ClickHouse: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 23:20:05,237 - ERROR - Error in processing queries\test3.py: Error HTTPSConnectionPool(host='di33kgplgc.germanywestcentral.azure.clickhouse.cloud', port=8443): Max retries exceeded with url: /? (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))) executing HTTP request attempt 1 (https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443)
2025-03-27 23:20:05,237 - INFO - All query files processed successfully!
2025-03-27 23:23:43,423 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 23:23:43,424 - INFO - Starting data processing for queries\test1.py
2025-03-27 23:24:20,532 - INFO - Connected to ClickHouse database.
2025-03-27 23:24:25,910 - INFO - Connected to ClickHouse database.
2025-03-27 23:24:25,910 - ERROR - Error in ensuring table: 'HttpClient' object has no attribute 'execute'
2025-03-27 23:24:25,910 - ERROR - Error in processing queries\test1.py: 'HttpClient' object has no attribute 'execute'
2025-03-27 23:24:25,910 - INFO - Starting data processing for queries\test2.py
2025-03-27 23:24:27,784 - INFO - Connected to ClickHouse database.
2025-03-27 23:24:29,010 - INFO - Connected to ClickHouse database.
2025-03-27 23:24:29,010 - ERROR - Error in ensuring table: 'HttpClient' object has no attribute 'execute'
2025-03-27 23:24:29,010 - ERROR - Error in processing queries\test2.py: 'HttpClient' object has no attribute 'execute'
2025-03-27 23:24:29,014 - INFO - Starting data processing for queries\test3.py
2025-03-27 23:24:29,934 - INFO - Connected to ClickHouse database.
2025-03-27 23:24:31,056 - INFO - Connected to ClickHouse database.
2025-03-27 23:24:31,056 - ERROR - Error in ensuring table: 'HttpClient' object has no attribute 'execute'
2025-03-27 23:24:31,056 - ERROR - Error in processing queries\test3.py: 'HttpClient' object has no attribute 'execute'
2025-03-27 23:24:31,058 - INFO - All query files processed successfully!
2025-03-27 23:25:49,000 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 23:25:49,004 - INFO - Starting data processing for queries\test1.py
2025-03-27 23:25:56,849 - INFO - Connected to ClickHouse database.
2025-03-27 23:25:57,812 - INFO - Connected to ClickHouse database.
2025-03-27 23:25:58,034 - INFO - Table test1 checked/created successfully in 'AH' database.
2025-03-27 23:25:59,584 - INFO - Connected to ClickHouse database.
2025-03-27 23:25:59,586 - ERROR - Error in fetching data: 'HttpClient' object has no attribute 'cursor'
2025-03-27 23:25:59,586 - INFO - MySQL connection closed.
2025-03-27 23:25:59,586 - ERROR - Error in processing queries\test1.py: 'HttpClient' object has no attribute 'cursor'
2025-03-27 23:25:59,589 - INFO - Starting data processing for queries\test2.py
2025-03-27 23:26:00,317 - INFO - Connected to ClickHouse database.
2025-03-27 23:26:01,160 - INFO - Connected to ClickHouse database.
2025-03-27 23:26:01,376 - INFO - Table test2 checked/created successfully in 'AH' database.
2025-03-27 23:26:04,110 - INFO - Connected to ClickHouse database.
2025-03-27 23:26:04,113 - ERROR - Error in fetching data: 'HttpClient' object has no attribute 'cursor'
2025-03-27 23:26:04,114 - INFO - MySQL connection closed.
2025-03-27 23:26:04,114 - ERROR - Error in processing queries\test2.py: 'HttpClient' object has no attribute 'cursor'
2025-03-27 23:26:04,116 - INFO - Starting data processing for queries\test3.py
2025-03-27 23:26:07,900 - INFO - Connected to ClickHouse database.
2025-03-27 23:26:09,150 - INFO - Connected to ClickHouse database.
2025-03-27 23:26:09,744 - INFO - Table product checked/created successfully in 'AH' database.
2025-03-27 23:26:10,430 - INFO - Connected to ClickHouse database.
2025-03-27 23:26:10,430 - ERROR - Error in fetching data: 'HttpClient' object has no attribute 'cursor'
2025-03-27 23:26:10,430 - INFO - MySQL connection closed.
2025-03-27 23:26:10,430 - ERROR - Error in processing queries\test3.py: 'HttpClient' object has no attribute 'cursor'
2025-03-27 23:26:10,432 - INFO - All query files processed successfully!
2025-03-27 23:27:57,853 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 23:27:57,853 - INFO - Starting data processing for queries\test1.py
2025-03-27 23:28:05,481 - INFO - Connected to ClickHouse database.
2025-03-27 23:28:06,110 - INFO - Connected to ClickHouse database.
2025-03-27 23:28:06,305 - INFO - Table test1 checked/created successfully in 'AH' database.
2025-03-27 23:28:13,663 - INFO - Connected to ClickHouse database.
2025-03-27 23:28:13,873 - INFO - Query execution completed
2025-03-27 23:28:13,873 - INFO - Data fetched successfully from database.
2025-03-27 23:28:13,873 - INFO - 28 rows fetched
2025-03-27 23:28:13,875 - INFO - MySQL connection closed.
2025-03-27 23:28:20,049 - INFO - Connected to ClickHouse database.
2025-03-27 23:28:21,741 - INFO - Final data inserted successfully into 'test1' in 'AH' database.
2025-03-27 23:28:21,743 - INFO - Data processing pipeline for queries\test1.py completed successfully!
2025-03-27 23:28:21,751 - INFO - Starting data processing for queries\test2.py
2025-03-27 23:28:26,613 - INFO - Connected to ClickHouse database.
2025-03-27 23:28:27,656 - INFO - Connected to ClickHouse database.
2025-03-27 23:28:27,916 - INFO - Table test2 checked/created successfully in 'AH' database.
2025-03-27 23:28:30,430 - INFO - Connected to ClickHouse database.
2025-03-27 23:28:30,693 - INFO - Query execution completed
2025-03-27 23:28:30,694 - INFO - Data fetched successfully from database.
2025-03-27 23:28:30,694 - INFO - 4 rows fetched
2025-03-27 23:28:30,694 - INFO - MySQL connection closed.
2025-03-27 23:28:32,596 - INFO - Connected to ClickHouse database.
2025-03-27 23:28:33,008 - INFO - Final data inserted successfully into 'test2' in 'AH' database.
2025-03-27 23:28:33,018 - INFO - Data processing pipeline for queries\test2.py completed successfully!
2025-03-27 23:28:33,019 - INFO - Starting data processing for queries\test3.py
2025-03-27 23:28:33,710 - INFO - Connected to ClickHouse database.
2025-03-27 23:28:34,530 - INFO - Connected to ClickHouse database.
2025-03-27 23:28:34,713 - INFO - Table product checked/created successfully in 'AH' database.
2025-03-27 23:28:35,520 - INFO - Connected to ClickHouse database.
2025-03-27 23:28:35,684 - ERROR - Error in fetching data: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 60
 Code: 60. DB::Exception: Unknown table expression identifier 'products' in scope SELECT id, product_name, next_screen, created_at FROM products. (UNKNOWN_TABLE) (version 24.10.1.11464 (official build))

2025-03-27 23:28:35,686 - INFO - MySQL connection closed.
2025-03-27 23:28:35,686 - ERROR - Error in processing queries\test3.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 60
 Code: 60. DB::Exception: Unknown table expression identifier 'products' in scope SELECT id, product_name, next_screen, created_at FROM products. (UNKNOWN_TABLE) (version 24.10.1.11464 (official build))

2025-03-27 23:28:35,688 - INFO - All query files processed successfully!
2025-03-27 23:37:16,564 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 23:37:16,565 - INFO - Starting data processing for queries\test1.py
2025-03-27 23:37:20,190 - INFO - Connected to ClickHouse database.
2025-03-27 23:37:21,109 - INFO - Table test1 checked/created successfully in 'AH' database.
2025-03-27 23:37:22,088 - INFO - Query execution completed
2025-03-27 23:37:22,088 - INFO - Data fetched successfully from database.
2025-03-27 23:37:22,090 - INFO - 28 rows fetched
2025-03-27 23:37:22,090 - INFO - MySQL connection closed.
2025-03-27 23:37:23,504 - INFO - Final data inserted successfully into 'test1' in 'AH' database.
2025-03-27 23:37:23,504 - INFO - Data processing pipeline for queries\test1.py completed successfully!
2025-03-27 23:37:23,506 - INFO - Starting data processing for queries\test2.py
2025-03-27 23:37:24,385 - INFO - Connected to ClickHouse database.
2025-03-27 23:37:25,220 - INFO - Table test2 checked/created successfully in 'AH' database.
2025-03-27 23:37:26,376 - INFO - Query execution completed
2025-03-27 23:37:26,376 - INFO - Data fetched successfully from database.
2025-03-27 23:37:26,376 - INFO - 4 rows fetched
2025-03-27 23:37:26,376 - INFO - MySQL connection closed.
2025-03-27 23:37:27,490 - INFO - Final data inserted successfully into 'test2' in 'AH' database.
2025-03-27 23:37:27,492 - INFO - Data processing pipeline for queries\test2.py completed successfully!
2025-03-27 23:37:27,493 - INFO - Starting data processing for queries\test3.py
2025-03-27 23:37:28,034 - INFO - Connected to ClickHouse database.
2025-03-27 23:37:28,809 - INFO - Table product checked/created successfully in 'AH' database.
2025-03-27 23:37:29,931 - ERROR - Error in fetching data: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 60
 Code: 60. DB::Exception: Unknown table expression identifier 'products' in scope SELECT id, product_name, next_screen, created_at FROM products. (UNKNOWN_TABLE) (version 24.10.1.11464 (official build))

2025-03-27 23:37:29,931 - INFO - MySQL connection closed.
2025-03-27 23:37:29,933 - ERROR - Error in processing queries\test3.py: HTTPDriver for https://di33kgplgc.germanywestcentral.azure.clickhouse.cloud:8443 received ClickHouse error code 60
 Code: 60. DB::Exception: Unknown table expression identifier 'products' in scope SELECT id, product_name, next_screen, created_at FROM products. (UNKNOWN_TABLE) (version 24.10.1.11464 (official build))

2025-03-27 23:37:29,933 - INFO - All query files processed successfully!
2025-03-27 23:38:15,595 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 23:38:15,597 - INFO - Starting data processing for queries\test1.py
2025-03-27 23:38:19,947 - INFO - Connected to ClickHouse database.
2025-03-27 23:38:21,174 - INFO - Table test1 checked/created successfully in 'AH' database.
2025-03-27 23:38:22,459 - INFO - Query execution completed
2025-03-27 23:38:22,459 - INFO - Data fetched successfully from database.
2025-03-27 23:38:22,459 - INFO - 28 rows fetched
2025-03-27 23:38:22,459 - INFO - MySQL connection closed.
2025-03-27 23:38:23,462 - INFO - Final data inserted successfully into 'test1' in 'AH' database.
2025-03-27 23:38:23,464 - INFO - Data processing pipeline for queries\test1.py completed successfully!
2025-03-27 23:38:23,466 - INFO - Starting data processing for queries\test2.py
2025-03-27 23:38:24,053 - INFO - Connected to ClickHouse database.
2025-03-27 23:38:24,858 - INFO - Table test2 checked/created successfully in 'AH' database.
2025-03-27 23:38:25,800 - INFO - Query execution completed
2025-03-27 23:38:25,802 - INFO - Data fetched successfully from database.
2025-03-27 23:38:25,804 - INFO - 4 rows fetched
2025-03-27 23:38:25,804 - INFO - MySQL connection closed.
2025-03-27 23:38:26,882 - INFO - Final data inserted successfully into 'test2' in 'AH' database.
2025-03-27 23:38:26,882 - INFO - Data processing pipeline for queries\test2.py completed successfully!
2025-03-27 23:38:26,906 - INFO - Starting data processing for queries\test3.py
2025-03-27 23:38:27,656 - INFO - Connected to ClickHouse database.
2025-03-27 23:38:28,388 - INFO - Table product checked/created successfully in 'AH' database.
2025-03-27 23:38:29,143 - INFO - Query execution completed
2025-03-27 23:38:29,143 - WARNING - No data returned from the query.
2025-03-27 23:38:29,143 - INFO - MySQL connection closed.
2025-03-27 23:38:29,878 - INFO - Final data inserted successfully into 'product' in 'AH' database.
2025-03-27 23:38:29,878 - INFO - Data processing pipeline for queries\test3.py completed successfully!
2025-03-27 23:38:29,878 - INFO - All query files processed successfully!
2025-03-27 23:40:04,002 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 23:40:04,004 - INFO - Starting data processing for queries\test1.py
2025-03-27 23:40:26,200 - INFO - Connected to ClickHouse database.
2025-03-27 23:40:28,089 - INFO - Table test1 checked/created successfully in 'AH' database.
2025-03-27 23:40:28,165 - INFO - Connected to MySQL database.
2025-03-27 23:40:28,167 - ERROR - Error in fetching data: 'Connection' object has no attribute 'query_df'
2025-03-27 23:40:28,168 - INFO - MySQL connection closed.
2025-03-27 23:40:28,168 - ERROR - Error in processing queries\test1.py: 'Connection' object has no attribute 'query_df'
2025-03-27 23:40:28,168 - INFO - Starting data processing for queries\test2.py
2025-03-27 23:40:28,705 - INFO - Connected to ClickHouse database.
2025-03-27 23:40:29,624 - INFO - Table test2 checked/created successfully in 'AH' database.
2025-03-27 23:40:29,627 - INFO - Connected to MySQL database.
2025-03-27 23:40:29,631 - ERROR - Error in fetching data: 'Connection' object has no attribute 'query_df'
2025-03-27 23:40:29,632 - INFO - MySQL connection closed.
2025-03-27 23:40:29,632 - ERROR - Error in processing queries\test2.py: 'Connection' object has no attribute 'query_df'
2025-03-27 23:40:29,638 - INFO - Starting data processing for queries\test3.py
2025-03-27 23:40:30,395 - INFO - Connected to ClickHouse database.
2025-03-27 23:40:31,305 - INFO - Table product checked/created successfully in 'AH' database.
2025-03-27 23:40:31,309 - INFO - Connected to MySQL database.
2025-03-27 23:40:31,309 - ERROR - Error in fetching data: 'Connection' object has no attribute 'query_df'
2025-03-27 23:40:31,309 - INFO - MySQL connection closed.
2025-03-27 23:40:31,312 - ERROR - Error in processing queries\test3.py: 'Connection' object has no attribute 'query_df'
2025-03-27 23:40:31,313 - INFO - All query files processed successfully!
2025-03-27 23:44:15,605 - INFO - Starting the data processing pipeline for all query files.
2025-03-27 23:44:15,611 - INFO - Starting data processing for queries\test1.py
2025-03-27 23:45:10,308 - INFO - Connected to ClickHouse database.
2025-03-27 23:45:20,147 - INFO - Table test1 checked/created successfully in 'AH' database.
2025-03-27 23:45:20,153 - INFO - Connected to MySQL database.
2025-03-27 23:45:20,153 - INFO - Connected to MySQL database.
2025-03-27 23:45:22,546 - INFO - Query execution completed
2025-03-27 23:45:22,548 - INFO - Data fetched successfully from database.
2025-03-27 23:45:22,550 - INFO - 854 rows fetched
2025-03-27 23:45:22,550 - INFO - MySQL connection closed.
2025-03-27 23:45:29,414 - INFO - Final data inserted successfully into 'test1' in 'AH' database.
2025-03-27 23:45:29,414 - INFO - Data processing pipeline for queries\test1.py completed successfully!
2025-03-27 23:45:29,414 - INFO - Starting data processing for queries\test2.py
2025-03-27 23:45:32,821 - INFO - Connected to ClickHouse database.
2025-03-27 23:45:45,162 - INFO - Table test2 checked/created successfully in 'AH' database.
2025-03-27 23:45:45,187 - INFO - Connected to MySQL database.
2025-03-27 23:45:45,187 - INFO - Connected to MySQL database.
2025-03-27 23:45:46,401 - INFO - Query execution completed
2025-03-27 23:45:46,403 - INFO - Data fetched successfully from database.
2025-03-27 23:45:46,403 - INFO - 122 rows fetched
2025-03-27 23:45:46,404 - INFO - MySQL connection closed.
2025-03-27 23:45:49,895 - INFO - Final data inserted successfully into 'test2' in 'AH' database.
2025-03-27 23:45:49,897 - INFO - Data processing pipeline for queries\test2.py completed successfully!
2025-03-27 23:45:49,900 - INFO - Starting data processing for queries\test3.py
2025-03-27 23:45:52,107 - INFO - Connected to ClickHouse database.
2025-03-27 23:45:53,549 - INFO - Table product checked/created successfully in 'AH' database.
2025-03-27 23:45:53,572 - INFO - Connected to MySQL database.
2025-03-27 23:45:53,572 - INFO - Connected to MySQL database.
2025-03-27 23:45:53,607 - INFO - Query execution completed
2025-03-27 23:45:53,609 - INFO - Data fetched successfully from database.
2025-03-27 23:45:53,609 - INFO - 5 rows fetched
2025-03-27 23:45:53,609 - INFO - MySQL connection closed.
2025-03-27 23:45:55,131 - INFO - Final data inserted successfully into 'product' in 'AH' database.
2025-03-27 23:45:55,131 - INFO - Data processing pipeline for queries\test3.py completed successfully!
2025-03-27 23:45:55,136 - INFO - All query files processed successfully!
